/*
 * generated by Xtext 2.38.0
 */
package fr.inria.kairos.influence.ide;


/**
 * Use this class to register ide components.
 */
public class InfluenceDSLIdeModule extends AbstractInfluenceDSLIdeModule {
}
