/**
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.formatting2;

import com.google.inject.Inject;
import fr.inria.kairos.influence.metamodel.AbstractInfluence;
import fr.inria.kairos.influence.metamodel.DesignArtifact;
import fr.inria.kairos.influence.metamodel.Influence;
import fr.inria.kairos.influence.metamodel.InfluenceModel;
import fr.inria.kairos.influence.metamodel.PhysicalPhenomena;
import fr.inria.kairos.influence.metamodel.Requirement;
import fr.inria.kairos.influence.metamodel.SystemResponse;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class InfluenceDSLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private InfluenceDSLGrammarAccess _influenceDSLGrammarAccess;

  protected void _format(final InfluenceModel influenceModel, @Extension final IFormattableDocument document) {
    EList<AbstractInfluence> _ownedInfluences = influenceModel.getOwnedInfluences();
    for (final AbstractInfluence influence : _ownedInfluences) {
      document.<AbstractInfluence>format(influence);
    }
    EList<Requirement> _ownedRequirements = influenceModel.getOwnedRequirements();
    for (final Requirement requirementSatisfaction : _ownedRequirements) {
      document.<Requirement>format(requirementSatisfaction);
    }
    EList<PhysicalPhenomena> _ownedPhysicalPhenomena = influenceModel.getOwnedPhysicalPhenomena();
    for (final PhysicalPhenomena cyberPhysicalPhenomena : _ownedPhysicalPhenomena) {
      document.<PhysicalPhenomena>format(cyberPhysicalPhenomena);
    }
    EList<DesignArtifact> _ownedArtifacts = influenceModel.getOwnedArtifacts();
    for (final DesignArtifact artifact : _ownedArtifacts) {
      document.<DesignArtifact>format(artifact);
    }
  }

  protected void _format(final Influence influence, @Extension final IFormattableDocument document) {
    EList<SystemResponse> _affects = influence.getAffects();
    for (final SystemResponse systemResponse : _affects) {
      document.<SystemResponse>format(systemResponse);
    }
    EList<SystemResponse> _affects_1 = influence.getAffects();
    for (final SystemResponse systemResponse_1 : _affects_1) {
      document.<SystemResponse>format(systemResponse_1);
    }
  }

  @XbaseGenerated
  public void format(final Object influence, final IFormattableDocument document) {
    if (influence instanceof Influence) {
      _format((Influence)influence, document);
      return;
    } else if (influence instanceof XtextResource) {
      _format((XtextResource)influence, document);
      return;
    } else if (influence instanceof InfluenceModel) {
      _format((InfluenceModel)influence, document);
      return;
    } else if (influence instanceof EObject) {
      _format((EObject)influence, document);
      return;
    } else if (influence == null) {
      _format((Void)null, document);
      return;
    } else if (influence != null) {
      _format(influence, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(influence, document).toString());
    }
  }
}
