/**
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.formatting2;

import com.google.inject.Inject;
import fr.inria.kairos.influence.metamodel.Influence;
import fr.inria.kairos.influence.metamodel.InfluenceFunction;
import fr.inria.kairos.influence.metamodel.InfluenceModel;
import fr.inria.kairos.influence.metamodel.Participant;
import fr.inria.kairos.influence.metamodel.SystemResponseProperty;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class InfluenceDSLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private /* InfluenceDSLGrammarAccess */Object _influenceDSLGrammarAccess;

  protected void _format(final InfluenceModel model, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ownedRequirements is undefined for the type InfluenceModel"
      + "\nformat cannot be resolved");
  }

  protected void _format(final Influence influence, @Extension final IFormattableDocument document) {
    InfluenceFunction _ownedInfluenceFunction = influence.getOwnedInfluenceFunction();
    if (_ownedInfluenceFunction!=null) {
      document.<InfluenceFunction>format(_ownedInfluenceFunction);
    }
    EList<Participant> _ownedParticipants = influence.getOwnedParticipants();
    for (final Participant p : _ownedParticipants) {
      document.<Participant>format(p);
    }
    SystemResponseProperty _outputSRP = influence.getOutputSRP();
    if (_outputSRP!=null) {
      document.<SystemResponseProperty>format(_outputSRP);
    }
  }

  @XbaseGenerated
  public void format(final Object influence, final IFormattableDocument document) {
    if (influence instanceof Influence) {
      _format((Influence)influence, document);
      return;
    } else if (influence instanceof XtextResource) {
      _format((XtextResource)influence, document);
      return;
    } else if (influence instanceof InfluenceModel) {
      _format((InfluenceModel)influence, document);
      return;
    } else if (influence instanceof EObject) {
      _format((EObject)influence, document);
      return;
    } else if (influence == null) {
      _format((Void)null, document);
      return;
    } else if (influence != null) {
      _format(influence, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(influence, document).toString());
    }
  }
}
