/*
 * generated by Xtext 2.39.0
 */
package fr.inria.kairos.influence.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class InfluenceDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class InfluenceModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.InfluenceModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInfluenceModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInfluenceModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cOwnedArtifactsAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cOwnedArtifactsDesignArtifactParserRuleCall_3_0_0 = (RuleCall)cOwnedArtifactsAssignment_3_0.eContents().get(0);
		private final Assignment cOwnedRequirementsAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cOwnedRequirementsRequirementSatisfactionParserRuleCall_3_1_0 = (RuleCall)cOwnedRequirementsAssignment_3_1.eContents().get(0);
		private final Assignment cOwnedPhysicalPhenomenaAssignment_3_2 = (Assignment)cAlternatives_3.eContents().get(2);
		private final RuleCall cOwnedPhysicalPhenomenaPhysicalPhenomenaParserRuleCall_3_2_0 = (RuleCall)cOwnedPhysicalPhenomenaAssignment_3_2.eContents().get(0);
		private final Assignment cOwnedInfluencesAssignment_3_3 = (Assignment)cAlternatives_3.eContents().get(3);
		private final RuleCall cOwnedInfluencesAbstractInfluenceParserRuleCall_3_3_0 = (RuleCall)cOwnedInfluencesAssignment_3_3.eContents().get(0);
		
		//InfluenceModel returns InfluenceModel:
		//    {InfluenceModel}
		//    'InfluenceModel' name=EString
		//        (ownedArtifacts+=DesignArtifact |
		//        ownedRequirements+=RequirementSatisfaction |
		//        ownedPhysicalPhenomena+=PhysicalPhenomena |
		//        ownedInfluences+=AbstractInfluence
		//        )*
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{InfluenceModel}
		//'InfluenceModel' name=EString
		//    (ownedArtifacts+=DesignArtifact |
		//    ownedRequirements+=RequirementSatisfaction |
		//    ownedPhysicalPhenomena+=PhysicalPhenomena |
		//    ownedInfluences+=AbstractInfluence
		//    )*
		public Group getGroup() { return cGroup; }
		
		//{InfluenceModel}
		public Action getInfluenceModelAction_0() { return cInfluenceModelAction_0; }
		
		//'InfluenceModel'
		public Keyword getInfluenceModelKeyword_1() { return cInfluenceModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//(ownedArtifacts+=DesignArtifact |
		//ownedRequirements+=RequirementSatisfaction |
		//ownedPhysicalPhenomena+=PhysicalPhenomena |
		//ownedInfluences+=AbstractInfluence
		//)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//ownedArtifacts+=DesignArtifact
		public Assignment getOwnedArtifactsAssignment_3_0() { return cOwnedArtifactsAssignment_3_0; }
		
		//DesignArtifact
		public RuleCall getOwnedArtifactsDesignArtifactParserRuleCall_3_0_0() { return cOwnedArtifactsDesignArtifactParserRuleCall_3_0_0; }
		
		//ownedRequirements+=RequirementSatisfaction
		public Assignment getOwnedRequirementsAssignment_3_1() { return cOwnedRequirementsAssignment_3_1; }
		
		//RequirementSatisfaction
		public RuleCall getOwnedRequirementsRequirementSatisfactionParserRuleCall_3_1_0() { return cOwnedRequirementsRequirementSatisfactionParserRuleCall_3_1_0; }
		
		//ownedPhysicalPhenomena+=PhysicalPhenomena
		public Assignment getOwnedPhysicalPhenomenaAssignment_3_2() { return cOwnedPhysicalPhenomenaAssignment_3_2; }
		
		//PhysicalPhenomena
		public RuleCall getOwnedPhysicalPhenomenaPhysicalPhenomenaParserRuleCall_3_2_0() { return cOwnedPhysicalPhenomenaPhysicalPhenomenaParserRuleCall_3_2_0; }
		
		//ownedInfluences+=AbstractInfluence
		public Assignment getOwnedInfluencesAssignment_3_3() { return cOwnedInfluencesAssignment_3_3; }
		
		//AbstractInfluence
		public RuleCall getOwnedInfluencesAbstractInfluenceParserRuleCall_3_3_0() { return cOwnedInfluencesAbstractInfluenceParserRuleCall_3_3_0; }
	}
	public class AbstractInfluenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.AbstractInfluence");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInfluenceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompositeInfluenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractInfluence returns AbstractInfluence:
		//    Influence | CompositeInfluence
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Influence | CompositeInfluence
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Influence
		public RuleCall getInfluenceParserRuleCall_0() { return cInfluenceParserRuleCall_0; }
		
		//CompositeInfluence
		public RuleCall getCompositeInfluenceParserRuleCall_1() { return cCompositeInfluenceParserRuleCall_1; }
	}
	public class CompositeInfluenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.CompositeInfluence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cInfluenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cNumberSignAsteriskAsteriskKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionEStringParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Keyword cAsteriskAsteriskNumberSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEncapsulateKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cInternalInfluencesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cInternalInfluencesAbstractInfluenceCrossReference_8_0 = (CrossReference)cInternalInfluencesAssignment_8.eContents().get(0);
		private final RuleCall cInternalInfluencesAbstractInfluenceEStringParserRuleCall_8_0_1 = (RuleCall)cInternalInfluencesAbstractInfluenceCrossReference_8_0.eContents().get(1);
		private final Assignment cOwnedFunctionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cOwnedFunctionCompositeFunctionParserRuleCall_9_0 = (RuleCall)cOwnedFunctionAssignment_9.eContents().get(0);
		private final Keyword cAffectsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cAffectsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cAffectsSystemResponseParserRuleCall_11_0 = (RuleCall)cAffectsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cAndKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cAffectsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cAffectsSystemResponseParserRuleCall_12_1_0 = (RuleCall)cAffectsAssignment_12_1.eContents().get(0);
		
		//CompositeInfluence returns CompositeInfluence:
		//    'Composite' 'Influence'    name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
		//    'encapsulate'
		//        (internalInfluences+=[AbstractInfluence|EString])*
		//     ownedFunction=CompositeFunction
		//    'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Composite' 'Influence'    name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
		//'encapsulate'
		//    (internalInfluences+=[AbstractInfluence|EString])*
		// ownedFunction=CompositeFunction
		//'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
		public Group getGroup() { return cGroup; }
		
		//'Composite'
		public Keyword getCompositeKeyword_0() { return cCompositeKeyword_0; }
		
		//'Influence'
		public Keyword getInfluenceKeyword_1() { return cInfluenceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'#**'
		public Keyword getNumberSignAsteriskAsteriskKeyword_3() { return cNumberSignAsteriskAsteriskKeyword_3; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_0() { return cDescriptionEStringParserRuleCall_4_0; }
		
		//( "," description+=EString)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//'**#'?
		public Keyword getAsteriskAsteriskNumberSignKeyword_6() { return cAsteriskAsteriskNumberSignKeyword_6; }
		
		//'encapsulate'
		public Keyword getEncapsulateKeyword_7() { return cEncapsulateKeyword_7; }
		
		//(internalInfluences+=[AbstractInfluence|EString])*
		public Assignment getInternalInfluencesAssignment_8() { return cInternalInfluencesAssignment_8; }
		
		//[AbstractInfluence|EString]
		public CrossReference getInternalInfluencesAbstractInfluenceCrossReference_8_0() { return cInternalInfluencesAbstractInfluenceCrossReference_8_0; }
		
		//EString
		public RuleCall getInternalInfluencesAbstractInfluenceEStringParserRuleCall_8_0_1() { return cInternalInfluencesAbstractInfluenceEStringParserRuleCall_8_0_1; }
		
		//ownedFunction=CompositeFunction
		public Assignment getOwnedFunctionAssignment_9() { return cOwnedFunctionAssignment_9; }
		
		//CompositeFunction
		public RuleCall getOwnedFunctionCompositeFunctionParserRuleCall_9_0() { return cOwnedFunctionCompositeFunctionParserRuleCall_9_0; }
		
		//'affects'
		public Keyword getAffectsKeyword_10() { return cAffectsKeyword_10; }
		
		//affects+=SystemResponse
		public Assignment getAffectsAssignment_11() { return cAffectsAssignment_11; }
		
		//SystemResponse
		public RuleCall getAffectsSystemResponseParserRuleCall_11_0() { return cAffectsSystemResponseParserRuleCall_11_0; }
		
		//( "and" affects+=SystemResponse)*
		public Group getGroup_12() { return cGroup_12; }
		
		//"and"
		public Keyword getAndKeyword_12_0() { return cAndKeyword_12_0; }
		
		//affects+=SystemResponse
		public Assignment getAffectsAssignment_12_1() { return cAffectsAssignment_12_1; }
		
		//SystemResponse
		public RuleCall getAffectsSystemResponseParserRuleCall_12_1_0() { return cAffectsSystemResponseParserRuleCall_12_1_0; }
	}
	public class InfluenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.Influence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInfluenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cNumberSignAsteriskAsteriskKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionEStringParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cAsteriskAsteriskNumberSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cOriginatorsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Alternatives cAlternatives_8 = (Alternatives)cGroup.eContents().get(8);
		private final Group cGroup_8_0 = (Group)cAlternatives_8.eContents().get(0);
		private final Keyword cArtifactKeyword_8_0_0 = (Keyword)cGroup_8_0.eContents().get(0);
		private final Assignment cOriginatorArtifactAssignment_8_0_1 = (Assignment)cGroup_8_0.eContents().get(1);
		private final CrossReference cOriginatorArtifactDesignArtifactCrossReference_8_0_1_0 = (CrossReference)cOriginatorArtifactAssignment_8_0_1.eContents().get(0);
		private final RuleCall cOriginatorArtifactDesignArtifactEStringParserRuleCall_8_0_1_0_1 = (RuleCall)cOriginatorArtifactDesignArtifactCrossReference_8_0_1_0.eContents().get(1);
		private final Group cGroup_8_1 = (Group)cAlternatives_8.eContents().get(1);
		private final Keyword cPhenomenaKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cOriginatorPhenomenaAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final CrossReference cOriginatorPhenomenaPhysicalPhenomenaCrossReference_8_1_1_0 = (CrossReference)cOriginatorPhenomenaAssignment_8_1_1.eContents().get(0);
		private final RuleCall cOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_8_1_1_0_1 = (RuleCall)cOriginatorPhenomenaPhysicalPhenomenaCrossReference_8_1_1_0.eContents().get(1);
		private final Group cGroup_8_2 = (Group)cAlternatives_8.eContents().get(2);
		private final Keyword cSystemKeyword_8_2_0 = (Keyword)cGroup_8_2.eContents().get(0);
		private final Keyword cResponseKeyword_8_2_1 = (Keyword)cGroup_8_2.eContents().get(1);
		private final Assignment cOriginatorSystemResponseAssignment_8_2_2 = (Assignment)cGroup_8_2.eContents().get(2);
		private final CrossReference cOriginatorSystemResponseSystemResponseCrossReference_8_2_2_0 = (CrossReference)cOriginatorSystemResponseAssignment_8_2_2.eContents().get(0);
		private final RuleCall cOriginatorSystemResponseSystemResponseEStringParserRuleCall_8_2_2_0_1 = (RuleCall)cOriginatorSystemResponseSystemResponseCrossReference_8_2_2_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAndKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Alternatives cAlternatives_9_1 = (Alternatives)cGroup_9.eContents().get(1);
		private final Group cGroup_9_1_0 = (Group)cAlternatives_9_1.eContents().get(0);
		private final Keyword cArtifactKeyword_9_1_0_0 = (Keyword)cGroup_9_1_0.eContents().get(0);
		private final Assignment cOriginatorArtifactAssignment_9_1_0_1 = (Assignment)cGroup_9_1_0.eContents().get(1);
		private final CrossReference cOriginatorArtifactDesignArtifactCrossReference_9_1_0_1_0 = (CrossReference)cOriginatorArtifactAssignment_9_1_0_1.eContents().get(0);
		private final RuleCall cOriginatorArtifactDesignArtifactEStringParserRuleCall_9_1_0_1_0_1 = (RuleCall)cOriginatorArtifactDesignArtifactCrossReference_9_1_0_1_0.eContents().get(1);
		private final Group cGroup_9_1_1 = (Group)cAlternatives_9_1.eContents().get(1);
		private final Keyword cPhenomenaKeyword_9_1_1_0 = (Keyword)cGroup_9_1_1.eContents().get(0);
		private final Assignment cOriginatorPhenomenaAssignment_9_1_1_1 = (Assignment)cGroup_9_1_1.eContents().get(1);
		private final CrossReference cOriginatorPhenomenaPhysicalPhenomenaCrossReference_9_1_1_1_0 = (CrossReference)cOriginatorPhenomenaAssignment_9_1_1_1.eContents().get(0);
		private final RuleCall cOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_9_1_1_1_0_1 = (RuleCall)cOriginatorPhenomenaPhysicalPhenomenaCrossReference_9_1_1_1_0.eContents().get(1);
		private final Group cGroup_9_1_2 = (Group)cAlternatives_9_1.eContents().get(2);
		private final Keyword cSystemKeyword_9_1_2_0 = (Keyword)cGroup_9_1_2.eContents().get(0);
		private final Keyword cResponseKeyword_9_1_2_1 = (Keyword)cGroup_9_1_2.eContents().get(1);
		private final Assignment cOriginatorSystemResponseAssignment_9_1_2_2 = (Assignment)cGroup_9_1_2.eContents().get(2);
		private final CrossReference cOriginatorSystemResponseSystemResponseCrossReference_9_1_2_2_0 = (CrossReference)cOriginatorSystemResponseAssignment_9_1_2_2.eContents().get(0);
		private final RuleCall cOriginatorSystemResponseSystemResponseEStringParserRuleCall_9_1_2_2_0_1 = (RuleCall)cOriginatorSystemResponseSystemResponseCrossReference_9_1_2_2_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cMetadataKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cLikelihoodKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Keyword cColonKeyword_10_2_1 = (Keyword)cGroup_10_2.eContents().get(1);
		private final Assignment cLikelihoodPerElementAssignment_10_2_2 = (Assignment)cGroup_10_2.eContents().get(2);
		private final RuleCall cLikelihoodPerElementEStringParserRuleCall_10_2_2_0 = (RuleCall)cLikelihoodPerElementAssignment_10_2_2.eContents().get(0);
		private final Group cGroup_10_2_3 = (Group)cGroup_10_2.eContents().get(3);
		private final Keyword cCommaKeyword_10_2_3_0 = (Keyword)cGroup_10_2_3.eContents().get(0);
		private final Assignment cLikelihoodPerElementAssignment_10_2_3_1 = (Assignment)cGroup_10_2_3.eContents().get(1);
		private final RuleCall cLikelihoodPerElementEStringParserRuleCall_10_2_3_1_0 = (RuleCall)cLikelihoodPerElementAssignment_10_2_3_1.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cConfidenceKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Keyword cColonKeyword_10_3_1 = (Keyword)cGroup_10_3.eContents().get(1);
		private final Assignment cConfidenceAssignment_10_3_2 = (Assignment)cGroup_10_3.eContents().get(2);
		private final RuleCall cConfidenceEStringParserRuleCall_10_3_2_0 = (RuleCall)cConfidenceAssignment_10_3_2.eContents().get(0);
		private final Group cGroup_10_3_3 = (Group)cGroup_10_3.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_3_0 = (Keyword)cGroup_10_3_3.eContents().get(0);
		private final Assignment cConfidenceAssignment_10_3_3_1 = (Assignment)cGroup_10_3_3.eContents().get(1);
		private final RuleCall cConfidenceEStringParserRuleCall_10_3_3_1_0 = (RuleCall)cConfidenceAssignment_10_3_3_1.eContents().get(0);
		private final Assignment cOwnedFunctionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cOwnedFunctionFunctionParserRuleCall_11_0 = (RuleCall)cOwnedFunctionAssignment_11.eContents().get(0);
		private final Keyword cAffectsKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cAffectsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cAffectsSystemResponseParserRuleCall_13_0 = (RuleCall)cAffectsAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cAndKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cAffectsAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cAffectsSystemResponseParserRuleCall_14_1_0 = (RuleCall)cAffectsAssignment_14_1.eContents().get(0);
		
		//Influence returns Influence:
		//    'Influence' name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
		//        'originators' ':' (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString]))
		//                          ( "and" (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString])))*
		//        ( 'metadata' ':' ( 'likelihood' ':' likelihoodPerElement+=EString (',' likelihoodPerElement+=EString)* )?
		//        (  'confidence' ':' confidence+=EString (',' confidence+=EString)* )?
		//    )?
		//        ownedFunction=Function
		//        'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Influence' name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
		//    'originators' ':' (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString]))
		//                      ( "and" (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString])))*
		//    ( 'metadata' ':' ( 'likelihood' ':' likelihoodPerElement+=EString (',' likelihoodPerElement+=EString)* )?
		//    (  'confidence' ':' confidence+=EString (',' confidence+=EString)* )?
		//)?
		//    ownedFunction=Function
		//    'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
		public Group getGroup() { return cGroup; }
		
		//'Influence'
		public Keyword getInfluenceKeyword_0() { return cInfluenceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'#**'
		public Keyword getNumberSignAsteriskAsteriskKeyword_2() { return cNumberSignAsteriskAsteriskKeyword_2; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_0() { return cDescriptionEStringParserRuleCall_3_0; }
		
		//( "," description+=EString)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'**#'?
		public Keyword getAsteriskAsteriskNumberSignKeyword_5() { return cAsteriskAsteriskNumberSignKeyword_5; }
		
		//'originators'
		public Keyword getOriginatorsKeyword_6() { return cOriginatorsKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//(("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString]))
		public Alternatives getAlternatives_8() { return cAlternatives_8; }
		
		//("artifact" originatorArtifact+=[DesignArtifact|EString])
		public Group getGroup_8_0() { return cGroup_8_0; }
		
		//"artifact"
		public Keyword getArtifactKeyword_8_0_0() { return cArtifactKeyword_8_0_0; }
		
		//originatorArtifact+=[DesignArtifact|EString]
		public Assignment getOriginatorArtifactAssignment_8_0_1() { return cOriginatorArtifactAssignment_8_0_1; }
		
		//[DesignArtifact|EString]
		public CrossReference getOriginatorArtifactDesignArtifactCrossReference_8_0_1_0() { return cOriginatorArtifactDesignArtifactCrossReference_8_0_1_0; }
		
		//EString
		public RuleCall getOriginatorArtifactDesignArtifactEStringParserRuleCall_8_0_1_0_1() { return cOriginatorArtifactDesignArtifactEStringParserRuleCall_8_0_1_0_1; }
		
		//("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString])
		public Group getGroup_8_1() { return cGroup_8_1; }
		
		//"phenomena"
		public Keyword getPhenomenaKeyword_8_1_0() { return cPhenomenaKeyword_8_1_0; }
		
		//originatorPhenomena+=[PhysicalPhenomena|EString]
		public Assignment getOriginatorPhenomenaAssignment_8_1_1() { return cOriginatorPhenomenaAssignment_8_1_1; }
		
		//[PhysicalPhenomena|EString]
		public CrossReference getOriginatorPhenomenaPhysicalPhenomenaCrossReference_8_1_1_0() { return cOriginatorPhenomenaPhysicalPhenomenaCrossReference_8_1_1_0; }
		
		//EString
		public RuleCall getOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_8_1_1_0_1() { return cOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_8_1_1_0_1; }
		
		//("system" "response" originatorSystemResponse+=[SystemResponse|EString])
		public Group getGroup_8_2() { return cGroup_8_2; }
		
		//"system"
		public Keyword getSystemKeyword_8_2_0() { return cSystemKeyword_8_2_0; }
		
		//"response"
		public Keyword getResponseKeyword_8_2_1() { return cResponseKeyword_8_2_1; }
		
		//originatorSystemResponse+=[SystemResponse|EString]
		public Assignment getOriginatorSystemResponseAssignment_8_2_2() { return cOriginatorSystemResponseAssignment_8_2_2; }
		
		//[SystemResponse|EString]
		public CrossReference getOriginatorSystemResponseSystemResponseCrossReference_8_2_2_0() { return cOriginatorSystemResponseSystemResponseCrossReference_8_2_2_0; }
		
		//EString
		public RuleCall getOriginatorSystemResponseSystemResponseEStringParserRuleCall_8_2_2_0_1() { return cOriginatorSystemResponseSystemResponseEStringParserRuleCall_8_2_2_0_1; }
		
		//( "and" (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString])))*
		public Group getGroup_9() { return cGroup_9; }
		
		//"and"
		public Keyword getAndKeyword_9_0() { return cAndKeyword_9_0; }
		
		//(("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString]))
		public Alternatives getAlternatives_9_1() { return cAlternatives_9_1; }
		
		//("artifact" originatorArtifact+=[DesignArtifact|EString])
		public Group getGroup_9_1_0() { return cGroup_9_1_0; }
		
		//"artifact"
		public Keyword getArtifactKeyword_9_1_0_0() { return cArtifactKeyword_9_1_0_0; }
		
		//originatorArtifact+=[DesignArtifact|EString]
		public Assignment getOriginatorArtifactAssignment_9_1_0_1() { return cOriginatorArtifactAssignment_9_1_0_1; }
		
		//[DesignArtifact|EString]
		public CrossReference getOriginatorArtifactDesignArtifactCrossReference_9_1_0_1_0() { return cOriginatorArtifactDesignArtifactCrossReference_9_1_0_1_0; }
		
		//EString
		public RuleCall getOriginatorArtifactDesignArtifactEStringParserRuleCall_9_1_0_1_0_1() { return cOriginatorArtifactDesignArtifactEStringParserRuleCall_9_1_0_1_0_1; }
		
		//("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString])
		public Group getGroup_9_1_1() { return cGroup_9_1_1; }
		
		//"phenomena"
		public Keyword getPhenomenaKeyword_9_1_1_0() { return cPhenomenaKeyword_9_1_1_0; }
		
		//originatorPhenomena+=[PhysicalPhenomena|EString]
		public Assignment getOriginatorPhenomenaAssignment_9_1_1_1() { return cOriginatorPhenomenaAssignment_9_1_1_1; }
		
		//[PhysicalPhenomena|EString]
		public CrossReference getOriginatorPhenomenaPhysicalPhenomenaCrossReference_9_1_1_1_0() { return cOriginatorPhenomenaPhysicalPhenomenaCrossReference_9_1_1_1_0; }
		
		//EString
		public RuleCall getOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_9_1_1_1_0_1() { return cOriginatorPhenomenaPhysicalPhenomenaEStringParserRuleCall_9_1_1_1_0_1; }
		
		//("system" "response" originatorSystemResponse+=[SystemResponse|EString])
		public Group getGroup_9_1_2() { return cGroup_9_1_2; }
		
		//"system"
		public Keyword getSystemKeyword_9_1_2_0() { return cSystemKeyword_9_1_2_0; }
		
		//"response"
		public Keyword getResponseKeyword_9_1_2_1() { return cResponseKeyword_9_1_2_1; }
		
		//originatorSystemResponse+=[SystemResponse|EString]
		public Assignment getOriginatorSystemResponseAssignment_9_1_2_2() { return cOriginatorSystemResponseAssignment_9_1_2_2; }
		
		//[SystemResponse|EString]
		public CrossReference getOriginatorSystemResponseSystemResponseCrossReference_9_1_2_2_0() { return cOriginatorSystemResponseSystemResponseCrossReference_9_1_2_2_0; }
		
		//EString
		public RuleCall getOriginatorSystemResponseSystemResponseEStringParserRuleCall_9_1_2_2_0_1() { return cOriginatorSystemResponseSystemResponseEStringParserRuleCall_9_1_2_2_0_1; }
		
		//    ( 'metadata' ':' ( 'likelihood' ':' likelihoodPerElement+=EString (',' likelihoodPerElement+=EString)* )?
		//    (  'confidence' ':' confidence+=EString (',' confidence+=EString)* )?
		//)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'metadata'
		public Keyword getMetadataKeyword_10_0() { return cMetadataKeyword_10_0; }
		
		//':'
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }
		
		//( 'likelihood' ':' likelihoodPerElement+=EString (',' likelihoodPerElement+=EString)* )?
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//'likelihood'
		public Keyword getLikelihoodKeyword_10_2_0() { return cLikelihoodKeyword_10_2_0; }
		
		//':'
		public Keyword getColonKeyword_10_2_1() { return cColonKeyword_10_2_1; }
		
		//likelihoodPerElement+=EString
		public Assignment getLikelihoodPerElementAssignment_10_2_2() { return cLikelihoodPerElementAssignment_10_2_2; }
		
		//EString
		public RuleCall getLikelihoodPerElementEStringParserRuleCall_10_2_2_0() { return cLikelihoodPerElementEStringParserRuleCall_10_2_2_0; }
		
		//(',' likelihoodPerElement+=EString)*
		public Group getGroup_10_2_3() { return cGroup_10_2_3; }
		
		//','
		public Keyword getCommaKeyword_10_2_3_0() { return cCommaKeyword_10_2_3_0; }
		
		//likelihoodPerElement+=EString
		public Assignment getLikelihoodPerElementAssignment_10_2_3_1() { return cLikelihoodPerElementAssignment_10_2_3_1; }
		
		//EString
		public RuleCall getLikelihoodPerElementEStringParserRuleCall_10_2_3_1_0() { return cLikelihoodPerElementEStringParserRuleCall_10_2_3_1_0; }
		
		//(  'confidence' ':' confidence+=EString (',' confidence+=EString)* )?
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//'confidence'
		public Keyword getConfidenceKeyword_10_3_0() { return cConfidenceKeyword_10_3_0; }
		
		//':'
		public Keyword getColonKeyword_10_3_1() { return cColonKeyword_10_3_1; }
		
		//confidence+=EString
		public Assignment getConfidenceAssignment_10_3_2() { return cConfidenceAssignment_10_3_2; }
		
		//EString
		public RuleCall getConfidenceEStringParserRuleCall_10_3_2_0() { return cConfidenceEStringParserRuleCall_10_3_2_0; }
		
		//(',' confidence+=EString)*
		public Group getGroup_10_3_3() { return cGroup_10_3_3; }
		
		//','
		public Keyword getCommaKeyword_10_3_3_0() { return cCommaKeyword_10_3_3_0; }
		
		//confidence+=EString
		public Assignment getConfidenceAssignment_10_3_3_1() { return cConfidenceAssignment_10_3_3_1; }
		
		//EString
		public RuleCall getConfidenceEStringParserRuleCall_10_3_3_1_0() { return cConfidenceEStringParserRuleCall_10_3_3_1_0; }
		
		//ownedFunction=Function
		public Assignment getOwnedFunctionAssignment_11() { return cOwnedFunctionAssignment_11; }
		
		//Function
		public RuleCall getOwnedFunctionFunctionParserRuleCall_11_0() { return cOwnedFunctionFunctionParserRuleCall_11_0; }
		
		//'affects'
		public Keyword getAffectsKeyword_12() { return cAffectsKeyword_12; }
		
		//affects+=SystemResponse
		public Assignment getAffectsAssignment_13() { return cAffectsAssignment_13; }
		
		//SystemResponse
		public RuleCall getAffectsSystemResponseParserRuleCall_13_0() { return cAffectsSystemResponseParserRuleCall_13_0; }
		
		//( "and" affects+=SystemResponse)*
		public Group getGroup_14() { return cGroup_14; }
		
		//"and"
		public Keyword getAndKeyword_14_0() { return cAndKeyword_14_0; }
		
		//affects+=SystemResponse
		public Assignment getAffectsAssignment_14_1() { return cAffectsAssignment_14_1; }
		
		//SystemResponse
		public RuleCall getAffectsSystemResponseParserRuleCall_14_1_0() { return cAffectsSystemResponseParserRuleCall_14_1_0; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDefinitionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDefinitionEStringParserRuleCall_3_0 = (RuleCall)cDefinitionAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Function:
		//  'fun' name=ID '(' definition=EString ')' ;
		@Override public ParserRule getRule() { return rule; }
		
		//'fun' name=ID '(' definition=EString ')'
		public Group getGroup() { return cGroup; }
		
		//'fun'
		public Keyword getFunKeyword_0() { return cFunKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//definition=EString
		public Assignment getDefinitionAssignment_3() { return cDefinitionAssignment_3; }
		
		//EString
		public RuleCall getDefinitionEStringParserRuleCall_3_0() { return cDefinitionEStringParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class CompositeFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.CompositeFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeFunKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInputsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cInputsSystemResponseCrossReference_3_0 = (CrossReference)cInputsAssignment_3.eContents().get(0);
		private final RuleCall cInputsSystemResponseEStringParserRuleCall_3_0_1 = (RuleCall)cInputsSystemResponseCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInputsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cInputsSystemResponseCrossReference_4_1_0 = (CrossReference)cInputsAssignment_4_1.eContents().get(0);
		private final RuleCall cInputsSystemResponseEStringParserRuleCall_4_1_0_1 = (RuleCall)cInputsSystemResponseCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CompositeFunction:
		//  'compositeFun' name=ID '(' inputs+=[SystemResponse|EString] (',' inputs+=[SystemResponse|EString])* ')' ;
		@Override public ParserRule getRule() { return rule; }
		
		//'compositeFun' name=ID '(' inputs+=[SystemResponse|EString] (',' inputs+=[SystemResponse|EString])* ')'
		public Group getGroup() { return cGroup; }
		
		//'compositeFun'
		public Keyword getCompositeFunKeyword_0() { return cCompositeFunKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//inputs+=[SystemResponse|EString]
		public Assignment getInputsAssignment_3() { return cInputsAssignment_3; }
		
		//[SystemResponse|EString]
		public CrossReference getInputsSystemResponseCrossReference_3_0() { return cInputsSystemResponseCrossReference_3_0; }
		
		//EString
		public RuleCall getInputsSystemResponseEStringParserRuleCall_3_0_1() { return cInputsSystemResponseEStringParserRuleCall_3_0_1; }
		
		//(',' inputs+=[SystemResponse|EString])*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//inputs+=[SystemResponse|EString]
		public Assignment getInputsAssignment_4_1() { return cInputsAssignment_4_1; }
		
		//[SystemResponse|EString]
		public CrossReference getInputsSystemResponseCrossReference_4_1_0() { return cInputsSystemResponseCrossReference_4_1_0; }
		
		//EString
		public RuleCall getInputsSystemResponseEStringParserRuleCall_4_1_0_1() { return cInputsSystemResponseEStringParserRuleCall_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class PhysicalPhenomenaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.PhysicalPhenomena");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPhenomenonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDescriptionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_2_1_0 = (RuleCall)cDescriptionAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cDescriptionAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_2_2_1_0 = (RuleCall)cDescriptionAssignment_2_2_1.eContents().get(0);
		
		//PhysicalPhenomena returns PhysicalPhenomena:
		//    'Phenomenon'
		//    name=EString
		//    (':' description+=EString ( "," description+=EString)* )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Phenomenon'
		//name=EString
		//(':' description+=EString ( "," description+=EString)* )?
		public Group getGroup() { return cGroup; }
		
		//'Phenomenon'
		public Keyword getPhenomenonKeyword_0() { return cPhenomenonKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//(':' description+=EString ( "," description+=EString)* )?
		public Group getGroup_2() { return cGroup_2; }
		
		//':'
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_2_1() { return cDescriptionAssignment_2_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_2_1_0() { return cDescriptionEStringParserRuleCall_2_1_0; }
		
		//( "," description+=EString)*
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }
		
		//description+=EString
		public Assignment getDescriptionAssignment_2_2_1() { return cDescriptionAssignment_2_2_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_2_2_1_0() { return cDescriptionEStringParserRuleCall_2_2_1_0; }
	}
	public class RequirementSatisfactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.RequirementSatisfaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRequirementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSatisfiedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cWhenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSatisfactionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSatisfactionEStringParserRuleCall_5_0 = (RuleCall)cSatisfactionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSatisfactionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSatisfactionEStringParserRuleCall_6_1_0 = (RuleCall)cSatisfactionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMetadataKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cColonKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMetadataAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMetadataEStringParserRuleCall_7_2_0 = (RuleCall)cMetadataAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cMetadataAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cMetadataEStringParserRuleCall_7_3_1_0 = (RuleCall)cMetadataAssignment_7_3_1.eContents().get(0);
		
		//RequirementSatisfaction returns Requirement:
		//    'Requirement' name=EString    ':'
		//    'satisfied' 'when' satisfaction+=EString ( "," satisfaction+=EString)*
		//      ( 'metadata' ':' metadata+=EString (',' metadata+=EString)* )?
		//      ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Requirement' name=EString    ':'
		//'satisfied' 'when' satisfaction+=EString ( "," satisfaction+=EString)*
		//  ( 'metadata' ':' metadata+=EString (',' metadata+=EString)* )?
		public Group getGroup() { return cGroup; }
		
		//'Requirement'
		public Keyword getRequirementKeyword_0() { return cRequirementKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'satisfied'
		public Keyword getSatisfiedKeyword_3() { return cSatisfiedKeyword_3; }
		
		//'when'
		public Keyword getWhenKeyword_4() { return cWhenKeyword_4; }
		
		//satisfaction+=EString
		public Assignment getSatisfactionAssignment_5() { return cSatisfactionAssignment_5; }
		
		//EString
		public RuleCall getSatisfactionEStringParserRuleCall_5_0() { return cSatisfactionEStringParserRuleCall_5_0; }
		
		//( "," satisfaction+=EString)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//satisfaction+=EString
		public Assignment getSatisfactionAssignment_6_1() { return cSatisfactionAssignment_6_1; }
		
		//EString
		public RuleCall getSatisfactionEStringParserRuleCall_6_1_0() { return cSatisfactionEStringParserRuleCall_6_1_0; }
		
		//( 'metadata' ':' metadata+=EString (',' metadata+=EString)* )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'metadata'
		public Keyword getMetadataKeyword_7_0() { return cMetadataKeyword_7_0; }
		
		//':'
		public Keyword getColonKeyword_7_1() { return cColonKeyword_7_1; }
		
		//metadata+=EString
		public Assignment getMetadataAssignment_7_2() { return cMetadataAssignment_7_2; }
		
		//EString
		public RuleCall getMetadataEStringParserRuleCall_7_2_0() { return cMetadataEStringParserRuleCall_7_2_0; }
		
		//(',' metadata+=EString)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//','
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//metadata+=EString
		public Assignment getMetadataAssignment_7_3_1() { return cMetadataAssignment_7_3_1; }
		
		//EString
		public RuleCall getMetadataEStringParserRuleCall_7_3_1_0() { return cMetadataEStringParserRuleCall_7_3_1_0; }
	}
	public class DesignArtifactElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.DesignArtifact");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDesignArtifactAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDesignArtifactKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRefAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRefEObjectCrossReference_4_0 = (CrossReference)cRefAssignment_4.eContents().get(0);
		private final RuleCall cRefEObjectQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cRefEObjectCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChangeabilityKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cChangeabilityAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cChangeabilityDOUBLETerminalRuleCall_5_2_0 = (RuleCall)cChangeabilityAssignment_5_2.eContents().get(0);
		
		//DesignArtifact returns DesignArtifact:
		//    {DesignArtifact}
		//    'DesignArtifact'
		//    name=EString "->" ref=[ecore::EObject|QualifiedName]
		//    ('changeability' '=' changeability=DOUBLE)?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{DesignArtifact}
		//'DesignArtifact'
		//name=EString "->" ref=[ecore::EObject|QualifiedName]
		//('changeability' '=' changeability=DOUBLE)?
		public Group getGroup() { return cGroup; }
		
		//{DesignArtifact}
		public Action getDesignArtifactAction_0() { return cDesignArtifactAction_0; }
		
		//'DesignArtifact'
		public Keyword getDesignArtifactKeyword_1() { return cDesignArtifactKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusGreaterThanSignKeyword_3; }
		
		//ref=[ecore::EObject|QualifiedName]
		public Assignment getRefAssignment_4() { return cRefAssignment_4; }
		
		//[ecore::EObject|QualifiedName]
		public CrossReference getRefEObjectCrossReference_4_0() { return cRefEObjectCrossReference_4_0; }
		
		//QualifiedName
		public RuleCall getRefEObjectQualifiedNameParserRuleCall_4_0_1() { return cRefEObjectQualifiedNameParserRuleCall_4_0_1; }
		
		//('changeability' '=' changeability=DOUBLE)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'changeability'
		public Keyword getChangeabilityKeyword_5_0() { return cChangeabilityKeyword_5_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }
		
		//changeability=DOUBLE
		public Assignment getChangeabilityAssignment_5_2() { return cChangeabilityAssignment_5_2; }
		
		//DOUBLE
		public RuleCall getChangeabilityDOUBLETerminalRuleCall_5_2_0() { return cChangeabilityDOUBLETerminalRuleCall_5_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SystemResponseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.SystemResponse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSystemResponseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cResponseKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsedKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cInKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUsedInAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cUsedInRequirementCrossReference_4_2_0 = (CrossReference)cUsedInAssignment_4_2.eContents().get(0);
		private final RuleCall cUsedInRequirementEStringParserRuleCall_4_2_0_1 = (RuleCall)cUsedInRequirementCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cAndKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cUsedInAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cUsedInRequirementCrossReference_4_3_1_0 = (CrossReference)cUsedInAssignment_4_3_1.eContents().get(0);
		private final RuleCall cUsedInRequirementEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cUsedInRequirementCrossReference_4_3_1_0.eContents().get(1);
		
		//SystemResponse returns SystemResponse:
		//    {SystemResponse}
		//    'system' 'response' name=EString
		//    ('used' 'in' usedIn+=[Requirement|EString] ("and" usedIn+=[Requirement|EString])*)?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemResponse}
		//'system' 'response' name=EString
		//('used' 'in' usedIn+=[Requirement|EString] ("and" usedIn+=[Requirement|EString])*)?
		public Group getGroup() { return cGroup; }
		
		//{SystemResponse}
		public Action getSystemResponseAction_0() { return cSystemResponseAction_0; }
		
		//'system'
		public Keyword getSystemKeyword_1() { return cSystemKeyword_1; }
		
		//'response'
		public Keyword getResponseKeyword_2() { return cResponseKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('used' 'in' usedIn+=[Requirement|EString] ("and" usedIn+=[Requirement|EString])*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'used'
		public Keyword getUsedKeyword_4_0() { return cUsedKeyword_4_0; }
		
		//'in'
		public Keyword getInKeyword_4_1() { return cInKeyword_4_1; }
		
		//usedIn+=[Requirement|EString]
		public Assignment getUsedInAssignment_4_2() { return cUsedInAssignment_4_2; }
		
		//[Requirement|EString]
		public CrossReference getUsedInRequirementCrossReference_4_2_0() { return cUsedInRequirementCrossReference_4_2_0; }
		
		//EString
		public RuleCall getUsedInRequirementEStringParserRuleCall_4_2_0_1() { return cUsedInRequirementEStringParserRuleCall_4_2_0_1; }
		
		//("and" usedIn+=[Requirement|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//"and"
		public Keyword getAndKeyword_4_3_0() { return cAndKeyword_4_3_0; }
		
		//usedIn+=[Requirement|EString]
		public Assignment getUsedInAssignment_4_3_1() { return cUsedInAssignment_4_3_1; }
		
		//[Requirement|EString]
		public CrossReference getUsedInRequirementCrossReference_4_3_1_0() { return cUsedInRequirementCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getUsedInRequirementEStringParserRuleCall_4_3_1_0_1() { return cUsedInRequirementEStringParserRuleCall_4_3_1_0_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//    ID ('.' ID)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class QualifiedNameWithWildCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.QualifiedNameWithWildCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildCard:
		//    QualifiedName '.*'?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }
		
		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}
	
	
	private final InfluenceModelElements pInfluenceModel;
	private final AbstractInfluenceElements pAbstractInfluence;
	private final CompositeInfluenceElements pCompositeInfluence;
	private final InfluenceElements pInfluence;
	private final FunctionElements pFunction;
	private final CompositeFunctionElements pCompositeFunction;
	private final PhysicalPhenomenaElements pPhysicalPhenomena;
	private final RequirementSatisfactionElements pRequirementSatisfaction;
	private final DesignArtifactElements pDesignArtifact;
	private final EStringElements pEString;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tEXP;
	private final SystemResponseElements pSystemResponse;
	private final QualifiedNameElements pQualifiedName;
	private final QualifiedNameWithWildCardElements pQualifiedNameWithWildCard;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public InfluenceDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pInfluenceModel = new InfluenceModelElements();
		this.pAbstractInfluence = new AbstractInfluenceElements();
		this.pCompositeInfluence = new CompositeInfluenceElements();
		this.pInfluence = new InfluenceElements();
		this.pFunction = new FunctionElements();
		this.pCompositeFunction = new CompositeFunctionElements();
		this.pPhysicalPhenomena = new PhysicalPhenomenaElements();
		this.pRequirementSatisfaction = new RequirementSatisfactionElements();
		this.pDesignArtifact = new DesignArtifactElements();
		this.pEString = new EStringElements();
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.DOUBLE");
		this.tEXP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.influence.InfluenceDSL.EXP");
		this.pSystemResponse = new SystemResponseElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pQualifiedNameWithWildCard = new QualifiedNameWithWildCardElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.inria.kairos.influence.InfluenceDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//InfluenceModel returns InfluenceModel:
	//    {InfluenceModel}
	//    'InfluenceModel' name=EString
	//        (ownedArtifacts+=DesignArtifact |
	//        ownedRequirements+=RequirementSatisfaction |
	//        ownedPhysicalPhenomena+=PhysicalPhenomena |
	//        ownedInfluences+=AbstractInfluence
	//        )*
	//    ;
	public InfluenceModelElements getInfluenceModelAccess() {
		return pInfluenceModel;
	}
	
	public ParserRule getInfluenceModelRule() {
		return getInfluenceModelAccess().getRule();
	}
	
	//AbstractInfluence returns AbstractInfluence:
	//    Influence | CompositeInfluence
	//;
	public AbstractInfluenceElements getAbstractInfluenceAccess() {
		return pAbstractInfluence;
	}
	
	public ParserRule getAbstractInfluenceRule() {
		return getAbstractInfluenceAccess().getRule();
	}
	
	//CompositeInfluence returns CompositeInfluence:
	//    'Composite' 'Influence'    name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
	//    'encapsulate'
	//        (internalInfluences+=[AbstractInfluence|EString])*
	//     ownedFunction=CompositeFunction
	//    'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
	//;
	public CompositeInfluenceElements getCompositeInfluenceAccess() {
		return pCompositeInfluence;
	}
	
	public ParserRule getCompositeInfluenceRule() {
		return getCompositeInfluenceAccess().getRule();
	}
	
	//Influence returns Influence:
	//    'Influence' name=EString '#**' description+=EString ( "," description+=EString)* '**#'?
	//        'originators' ':' (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString]))
	//                          ( "and" (("artifact" originatorArtifact+=[DesignArtifact|EString]) | ("phenomena" originatorPhenomena+=[PhysicalPhenomena|EString]) | ("system" "response" originatorSystemResponse+=[SystemResponse|EString])))*
	//        ( 'metadata' ':' ( 'likelihood' ':' likelihoodPerElement+=EString (',' likelihoodPerElement+=EString)* )?
	//        (  'confidence' ':' confidence+=EString (',' confidence+=EString)* )?
	//    )?
	//        ownedFunction=Function
	//        'affects' affects+=SystemResponse ( "and" affects+=SystemResponse)*
	//    ;
	public InfluenceElements getInfluenceAccess() {
		return pInfluence;
	}
	
	public ParserRule getInfluenceRule() {
		return getInfluenceAccess().getRule();
	}
	
	//Function:
	//  'fun' name=ID '(' definition=EString ')' ;
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//CompositeFunction:
	//  'compositeFun' name=ID '(' inputs+=[SystemResponse|EString] (',' inputs+=[SystemResponse|EString])* ')' ;
	public CompositeFunctionElements getCompositeFunctionAccess() {
		return pCompositeFunction;
	}
	
	public ParserRule getCompositeFunctionRule() {
		return getCompositeFunctionAccess().getRule();
	}
	
	//PhysicalPhenomena returns PhysicalPhenomena:
	//    'Phenomenon'
	//    name=EString
	//    (':' description+=EString ( "," description+=EString)* )?
	//    ;
	public PhysicalPhenomenaElements getPhysicalPhenomenaAccess() {
		return pPhysicalPhenomena;
	}
	
	public ParserRule getPhysicalPhenomenaRule() {
		return getPhysicalPhenomenaAccess().getRule();
	}
	
	//RequirementSatisfaction returns Requirement:
	//    'Requirement' name=EString    ':'
	//    'satisfied' 'when' satisfaction+=EString ( "," satisfaction+=EString)*
	//      ( 'metadata' ':' metadata+=EString (',' metadata+=EString)* )?
	//      ;
	public RequirementSatisfactionElements getRequirementSatisfactionAccess() {
		return pRequirementSatisfaction;
	}
	
	public ParserRule getRequirementSatisfactionRule() {
		return getRequirementSatisfactionAccess().getRule();
	}
	
	//DesignArtifact returns DesignArtifact:
	//    {DesignArtifact}
	//    'DesignArtifact'
	//    name=EString "->" ref=[ecore::EObject|QualifiedName]
	//    ('changeability' '=' changeability=DOUBLE)?
	//    ;
	public DesignArtifactElements getDesignArtifactAccess() {
		return pDesignArtifact;
	}
	
	public ParserRule getDesignArtifactRule() {
		return getDesignArtifactAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal DOUBLE returns ecore::EDouble:
	//    ('0'..'9')+ '.' ('0'..'9')+;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal fragment EXP: ('e'|'E') ('+'|'-')? INT;
	public TerminalRule getEXPRule() {
		return tEXP;
	}
	
	//SystemResponse returns SystemResponse:
	//    {SystemResponse}
	//    'system' 'response' name=EString
	//    ('used' 'in' usedIn+=[Requirement|EString] ("and" usedIn+=[Requirement|EString])*)?
	//    ;
	public SystemResponseElements getSystemResponseAccess() {
		return pSystemResponse;
	}
	
	public ParserRule getSystemResponseRule() {
		return getSystemResponseAccess().getRule();
	}
	
	//QualifiedName:
	//    ID ('.' ID)*
	//;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//QualifiedNameWithWildCard:
	//    QualifiedName '.*'?
	//;
	public QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return pQualifiedNameWithWildCard;
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
