/*
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.serializer;

import com.google.inject.Inject;
import fr.inria.kairos.influence.metamodel.Artifact;
import fr.inria.kairos.influence.metamodel.EmergentBehavior;
import fr.inria.kairos.influence.metamodel.Influence;
import fr.inria.kairos.influence.metamodel.InfluenceModel;
import fr.inria.kairos.influence.metamodel.MetamodelPackage;
import fr.inria.kairos.influence.metamodel.MultiPhenomenon;
import fr.inria.kairos.influence.metamodel.RequirementSatisfaction;
import fr.inria.kairos.influence.metamodel.SimplePhenomenon;
import fr.inria.kairos.influence.metamodel.SystemResponse;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class InfluenceDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MetamodelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MetamodelPackage.ARTIFACT:
				sequence_Artifact(context, (Artifact) semanticObject); 
				return; 
			case MetamodelPackage.EMERGENT_BEHAVIOR:
				sequence_EmergentBehavior(context, (EmergentBehavior) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE:
				sequence_Influence(context, (Influence) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE_MODEL:
				sequence_InfluenceModel(context, (InfluenceModel) semanticObject); 
				return; 
			case MetamodelPackage.MULTI_PHENOMENON:
				sequence_MultiPhenomenon(context, (MultiPhenomenon) semanticObject); 
				return; 
			case MetamodelPackage.REQUIREMENT_SATISFACTION:
				sequence_RequirementSatisfaction(context, (RequirementSatisfaction) semanticObject); 
				return; 
			case MetamodelPackage.SIMPLE_PHENOMENON:
				sequence_SimplePhenomenon(context, (SimplePhenomenon) semanticObject); 
				return; 
			case MetamodelPackage.SYSTEM_RESPONSE:
				sequence_SystemResponse(context, (SystemResponse) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Artifact returns Artifact
	 *
	 * Constraint:
	 *     (name=EString ref=[EObject|ID])
	 * </pre>
	 */
	protected void sequence_Artifact(ISerializationContext context, Artifact semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.ARTIFACT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.ARTIFACT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.ARTIFACT__REF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.ARTIFACT__REF));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getArtifactAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getArtifactAccess().getRefEObjectIDTerminalRuleCall_4_0_1(), semanticObject.eGet(MetamodelPackage.Literals.ARTIFACT__REF, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EmergentBehavior returns EmergentBehavior
	 *
	 * Constraint:
	 *     description=EString?
	 * </pre>
	 */
	protected void sequence_EmergentBehavior(ISerializationContext context, EmergentBehavior semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InfluenceModel returns InfluenceModel
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (
	 *             ownedArtifacts+=Artifact | 
	 *             ownedRequirementSatisfaction+=RequirementSatisfaction | 
	 *             ownedCyberPhysicalPhenomena+=CyberPhysicalPhenomena | 
	 *             ownedInfluences+=Influence
	 *         )*
	 *     )
	 * </pre>
	 */
	protected void sequence_InfluenceModel(ISerializationContext context, InfluenceModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Influence returns Influence
	 *
	 * Constraint:
	 *     (
	 *         description+=EString 
	 *         description+=EString* 
	 *         name=EString 
	 *         sourceArtifact+=[Artifact|ID] 
	 *         sourceArtifact+=[Artifact|ID]* 
	 *         sourcePhenomena+=[CyberPhysicalPhenomena|EString] 
	 *         sourcePhenomena+=[CyberPhysicalPhenomena|EString]* 
	 *         produces+=EmergentBehavior 
	 *         produces+=EmergentBehavior* 
	 *         affects+=SystemResponse 
	 *         affects+=SystemResponse* 
	 *         evaluatedBy+=[RequirementSatisfaction|EString] 
	 *         evaluatedBy+=[RequirementSatisfaction|EString]* 
	 *         targetArtifact+=[Artifact|ID] 
	 *         targetArtifact+=[Artifact|ID]*
	 *     )
	 * </pre>
	 */
	protected void sequence_Influence(ISerializationContext context, Influence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CyberPhysicalPhenomena returns MultiPhenomenon
	 *     MultiPhenomenon returns MultiPhenomenon
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (aggregationOf+=[CyberPhysicalPhenomena|EString] aggregationOf+=[CyberPhysicalPhenomena|EString]*)? 
	 *         (configuration+=EString configuration+=EString*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_MultiPhenomenon(ISerializationContext context, MultiPhenomenon semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RequirementSatisfaction returns RequirementSatisfaction
	 *
	 * Constraint:
	 *     (name=EString concerningRequirement=EString satisfaction+=EString satisfaction+=EString*)
	 * </pre>
	 */
	protected void sequence_RequirementSatisfaction(ISerializationContext context, RequirementSatisfaction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CyberPhysicalPhenomena returns SimplePhenomenon
	 *     SimplePhenomenon returns SimplePhenomenon
	 *
	 * Constraint:
	 *     (name=EString (configuration+=EString configuration+=EString*)?)
	 * </pre>
	 */
	protected void sequence_SimplePhenomenon(ISerializationContext context, SimplePhenomenon semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SystemResponse returns SystemResponse
	 *
	 * Constraint:
	 *     observation=EString?
	 * </pre>
	 */
	protected void sequence_SystemResponse(ISerializationContext context, SystemResponse semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
