/*
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InfluenceDSLRuntimeModule extends AbstractInfluenceDSLRuntimeModule {
	
	@Override
    public void configure(Binder binder) {
        super.configure(binder);
//        Multibinder<IResourceDescription.Event.Listener> listeners =
//                Multibinder.newSetBinder(binder, IResourceDescription.Event.Listener.class);
//            listeners.addBinding().to(MyIndexChangeListener.class);
            
        
//        binder.bind(IDefaultResourceDescriptionStrategy.class).to(InfluenceResourceDescriptionStrategy.class);

    }
	
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
	    return InfluenceQualifiedNameProvider.class;
	}
}
