/**
 */
package fr.inria.kairos.influence.metamodel.provider;

import fr.inria.kairos.influence.metamodel.util.MetamodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MetamodelItemProviderAdapterFactory extends MetamodelAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MetamodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.InfluenceModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InfluenceModelItemProvider influenceModelItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.InfluenceModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInfluenceModelAdapter() {
		if (influenceModelItemProvider == null) {
			influenceModelItemProvider = new InfluenceModelItemProvider(this);
		}

		return influenceModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.Influence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InfluenceItemProvider influenceItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.Influence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInfluenceAdapter() {
		if (influenceItemProvider == null) {
			influenceItemProvider = new InfluenceItemProvider(this);
		}

		return influenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.SRPInputParticipant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SRPInputParticipantItemProvider srpInputParticipantItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.SRPInputParticipant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSRPInputParticipantAdapter() {
		if (srpInputParticipantItemProvider == null) {
			srpInputParticipantItemProvider = new SRPInputParticipantItemProvider(this);
		}

		return srpInputParticipantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.ArtifactParticipant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactParticipantItemProvider artifactParticipantItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.ArtifactParticipant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactParticipantAdapter() {
		if (artifactParticipantItemProvider == null) {
			artifactParticipantItemProvider = new ArtifactParticipantItemProvider(this);
		}

		return artifactParticipantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.EnvironmentalFactorParticipant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentalFactorParticipantItemProvider environmentalFactorParticipantItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.EnvironmentalFactorParticipant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentalFactorParticipantAdapter() {
		if (environmentalFactorParticipantItemProvider == null) {
			environmentalFactorParticipantItemProvider = new EnvironmentalFactorParticipantItemProvider(this);
		}

		return environmentalFactorParticipantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.SatisfactionCriterion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SatisfactionCriterionItemProvider satisfactionCriterionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.SatisfactionCriterion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSatisfactionCriterionAdapter() {
		if (satisfactionCriterionItemProvider == null) {
			satisfactionCriterionItemProvider = new SatisfactionCriterionItemProvider(this);
		}

		return satisfactionCriterionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.CompositeInfluence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeInfluenceItemProvider compositeInfluenceItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.CompositeInfluence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeInfluenceAdapter() {
		if (compositeInfluenceItemProvider == null) {
			compositeInfluenceItemProvider = new CompositeInfluenceItemProvider(this);
		}

		return compositeInfluenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.DesignArtifact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignArtifactItemProvider designArtifactItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.DesignArtifact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDesignArtifactAdapter() {
		if (designArtifactItemProvider == null) {
			designArtifactItemProvider = new DesignArtifactItemProvider(this);
		}

		return designArtifactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.SystemResponseProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemResponsePropertyItemProvider systemResponsePropertyItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.SystemResponseProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemResponsePropertyAdapter() {
		if (systemResponsePropertyItemProvider == null) {
			systemResponsePropertyItemProvider = new SystemResponsePropertyItemProvider(this);
		}

		return systemResponsePropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.EnvironmentalFactor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentalFactorItemProvider environmentalFactorItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.EnvironmentalFactor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentalFactorAdapter() {
		if (environmentalFactorItemProvider == null) {
			environmentalFactorItemProvider = new EnvironmentalFactorItemProvider(this);
		}

		return environmentalFactorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.ParticipantRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantRangeItemProvider participantRangeItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.ParticipantRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantRangeAdapter() {
		if (participantRangeItemProvider == null) {
			participantRangeItemProvider = new ParticipantRangeItemProvider(this);
		}

		return participantRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.ScalarValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScalarValueItemProvider scalarValueItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.ScalarValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScalarValueAdapter() {
		if (scalarValueItemProvider == null) {
			scalarValueItemProvider = new ScalarValueItemProvider(this);
		}

		return scalarValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.RangeValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RangeValueItemProvider rangeValueItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.RangeValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRangeValueAdapter() {
		if (rangeValueItemProvider == null) {
			rangeValueItemProvider = new RangeValueItemProvider(this);
		}

		return rangeValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.NaturalLanguageFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NaturalLanguageFunctionItemProvider naturalLanguageFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.NaturalLanguageFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNaturalLanguageFunctionAdapter() {
		if (naturalLanguageFunctionItemProvider == null) {
			naturalLanguageFunctionItemProvider = new NaturalLanguageFunctionItemProvider(this);
		}

		return naturalLanguageFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.ParticipantImpactFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantImpactFunctionItemProvider participantImpactFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.ParticipantImpactFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantImpactFunctionAdapter() {
		if (participantImpactFunctionItemProvider == null) {
			participantImpactFunctionItemProvider = new ParticipantImpactFunctionItemProvider(this);
		}

		return participantImpactFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.ParticipantRelativeImpact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantRelativeImpactItemProvider participantRelativeImpactItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.ParticipantRelativeImpact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantRelativeImpactAdapter() {
		if (participantRelativeImpactItemProvider == null) {
			participantRelativeImpactItemProvider = new ParticipantRelativeImpactItemProvider(this);
		}

		return participantRelativeImpactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.AnalyticExpressionFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalyticExpressionFunctionItemProvider analyticExpressionFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.AnalyticExpressionFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalyticExpressionFunctionAdapter() {
		if (analyticExpressionFunctionItemProvider == null) {
			analyticExpressionFunctionItemProvider = new AnalyticExpressionFunctionItemProvider(this);
		}

		return analyticExpressionFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.MonotonicityTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MonotonicityTableItemProvider monotonicityTableItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.MonotonicityTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMonotonicityTableAdapter() {
		if (monotonicityTableItemProvider == null) {
			monotonicityTableItemProvider = new MonotonicityTableItemProvider(this);
		}

		return monotonicityTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.inria.kairos.influence.metamodel.MonotonicityRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MonotonicityRowItemProvider monotonicityRowItemProvider;

	/**
	 * This creates an adapter for a {@link fr.inria.kairos.influence.metamodel.MonotonicityRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMonotonicityRowAdapter() {
		if (monotonicityRowItemProvider == null) {
			monotonicityRowItemProvider = new MonotonicityRowItemProvider(this);
		}

		return monotonicityRowItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (influenceModelItemProvider != null)
			influenceModelItemProvider.dispose();
		if (influenceItemProvider != null)
			influenceItemProvider.dispose();
		if (srpInputParticipantItemProvider != null)
			srpInputParticipantItemProvider.dispose();
		if (artifactParticipantItemProvider != null)
			artifactParticipantItemProvider.dispose();
		if (environmentalFactorParticipantItemProvider != null)
			environmentalFactorParticipantItemProvider.dispose();
		if (satisfactionCriterionItemProvider != null)
			satisfactionCriterionItemProvider.dispose();
		if (compositeInfluenceItemProvider != null)
			compositeInfluenceItemProvider.dispose();
		if (designArtifactItemProvider != null)
			designArtifactItemProvider.dispose();
		if (systemResponsePropertyItemProvider != null)
			systemResponsePropertyItemProvider.dispose();
		if (environmentalFactorItemProvider != null)
			environmentalFactorItemProvider.dispose();
		if (participantRangeItemProvider != null)
			participantRangeItemProvider.dispose();
		if (scalarValueItemProvider != null)
			scalarValueItemProvider.dispose();
		if (rangeValueItemProvider != null)
			rangeValueItemProvider.dispose();
		if (naturalLanguageFunctionItemProvider != null)
			naturalLanguageFunctionItemProvider.dispose();
		if (participantImpactFunctionItemProvider != null)
			participantImpactFunctionItemProvider.dispose();
		if (participantRelativeImpactItemProvider != null)
			participantRelativeImpactItemProvider.dispose();
		if (analyticExpressionFunctionItemProvider != null)
			analyticExpressionFunctionItemProvider.dispose();
		if (monotonicityTableItemProvider != null)
			monotonicityTableItemProvider.dispose();
		if (monotonicityRowItemProvider != null)
			monotonicityRowItemProvider.dispose();
	}

}
