package fr.inria.kairos.influence.export;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;

@SuppressWarnings("all")
public class GentelellaDashboardExporter {
  public void export(final IFileSystemAccess2 fsa, final String basePath) {
    final String base = this.normalizeBasePath(basePath);
    fsa.generateFile((base + "/index.html"), this.page("Influence Dashboard", "overview"));
    fsa.generateFile((base + "/influences.html"), this.page("Influences", "influences"));
    fsa.generateFile((base + "/requirements.html"), this.page("Requirements", "requirements"));
    fsa.generateFile((base + "/developers.html"), this.page("Developer Views", "developers"));
    fsa.generateFile((base + "/tradeoffs.html"), this.page("Trade-offs", "tradeoffs"));
    fsa.generateFile((base + "/graph.html"), this.page("Influence Graph", "graph"));
    fsa.generateFile((base + "/assets/influence-dashboard.css"), this.css());
    fsa.generateFile((base + "/assets/influence-dashboard.js"), this.javascript());
  }

  private String normalizeBasePath(final String basePath) {
    if (((basePath == null) || basePath.trim().isEmpty())) {
      return "dashboard/site";
    }
    boolean _endsWith = basePath.endsWith("/");
    if (_endsWith) {
      int _length = basePath.length();
      int _minus = (_length - 1);
      return basePath.substring(0, _minus);
    }
    return basePath;
  }

  private String page(final String title, final String activePage) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!doctype html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<title>");
    _builder.append(title, "  ");
    _builder.append("</title>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<link href=\"assets/influence-dashboard.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("</head>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body data-page=\"");
    _builder.append(activePage);
    _builder.append("\">");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("<div class=\"app-shell\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<aside class=\"sidebar\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"brand\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"brand-icon\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-diagram-3\"></i>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<div class=\"brand-title\">Influence DSL</div>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<div class=\"brand-subtitle\">analysis dashboard</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<nav class=\"nav flex-column sidebar-nav\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"overview\" href=\"index.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-speedometer2\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Overview");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"influences\" href=\"influences.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-share\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Influences");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"requirements\" href=\"requirements.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-check2-square\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Requirements");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"developers\" href=\"developers.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-person-workspace\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Developer Views");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"tradeoffs\" href=\"tradeoffs.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-exclamation-triangle\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Trade-offs");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a class=\"nav-link\" data-nav=\"graph\" href=\"graph.html\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<i class=\"bi bi-node-plus\"></i>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Graph");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</nav>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</aside>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<main class=\"main-content\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<header class=\"topbar\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h1 id=\"page-title\">");
    _builder.append(title, "          ");
    _builder.append("</h1>");
    _builder.newLineIfNotEmpty();
    _builder.append("          ");
    _builder.append("<p id=\"page-subtitle\">Generated from Influence DSL analysis results.</p>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"status-pill\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<span class=\"status-dot\"></span>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("Static report");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</header>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<section id=\"dashboard-root\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"loading-card\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<div class=\"spinner-border text-primary\" role=\"status\"></div>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<p>Loading dashboard data...</p>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</section>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</main>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js\"></script>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<script src=\"assets/influence-dashboard.js\"></script>");
    _builder.newLine();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder.toString();
  }

  private String css() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(":root {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--sidebar-bg: #263238;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--sidebar-bg-2: #1f2a30;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--sidebar-text: #d9e3e7;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--sidebar-muted: #8fa3ad;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--accent: #26b99a;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--main-bg: #f5f7fa;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--card-bg: #ffffff;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--text-main: #263238;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--text-muted: #6c757d;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("--border: #e3e8ee;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("* {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("box-sizing: border-box;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("body {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: var(--main-bg);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-main);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-family: system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".app-shell {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("min-height: 100vh;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".sidebar {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 280px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: linear-gradient(180deg, var(--sidebar-bg), var(--sidebar-bg-2));");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--sidebar-text);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 22px 18px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("position: fixed;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("top: 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("bottom: 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("left: 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("overflow-y: auto;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".brand {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gap: 12px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("align-items: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin-bottom: 28px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-bottom: 20px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-bottom: 1px solid rgba(255, 255, 255, 0.1);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".brand-icon {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 44px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("height: 44px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 12px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: var(--accent);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("align-items: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("justify-content: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 22px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: white;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".brand-title {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-weight: 700;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 18px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".brand-subtitle {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--sidebar-muted);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 12px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("text-transform: uppercase;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("letter-spacing: 0.06em;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".sidebar-nav {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gap: 6px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".sidebar-nav .nav-link {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--sidebar-text);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 10px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 11px 12px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gap: 10px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("align-items: center;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".sidebar-nav .nav-link:hover,");
    _builder.newLine();
    _builder.append(".sidebar-nav .nav-link.active {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: rgba(255, 255, 255, 0.1);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: #ffffff;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".sidebar-nav .nav-link.active {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-left: 4px solid var(--accent);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".main-content {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin-left: 280px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 28px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: calc(100% - 280px);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".topbar {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("justify-content: space-between;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("align-items: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin-bottom: 24px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".topbar h1 {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 28px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-weight: 700;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".topbar p {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin: 6px 0 0;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-muted);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".status-pill {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: white;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border: 1px solid var(--border);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 999px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 8px 14px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 13px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-muted);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: flex;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("align-items: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gap: 8px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".status-dot {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 8px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("height: 8px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 999px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: var(--accent);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".card-box {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: var(--card-bg);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border: 1px solid var(--border);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 16px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 20px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("box-shadow: 0 8px 24px rgba(20, 35, 50, 0.05);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".metric-card {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: var(--card-bg);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border: 1px solid var(--border);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 16px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 18px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("box-shadow: 0 8px 24px rgba(20, 35, 50, 0.05);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".metric-label {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-muted);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 13px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("text-transform: uppercase;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("letter-spacing: 0.06em;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".metric-value {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 30px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-weight: 750;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin-top: 8px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".table {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("margin-bottom: 0;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".table thead th {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-muted);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 12px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("text-transform: uppercase;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("letter-spacing: 0.05em;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".badge-soft {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 999px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 5px 9px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-weight: 600;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: #eef8f5;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: #12856d;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".badge-warning-soft {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: #fff6e5;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: #9a6500;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".badge-danger-soft {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: #fdecec;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: #a73838;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".loading-card {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("background: white;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border: 1px solid var(--border);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-radius: 16px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 40px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: var(--text-muted);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".graph-list {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("max-height: 700px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("overflow: auto;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("code {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("color: #c7254e;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  private String javascript() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("const DATA_PATH = \"../data/dashboard-data.json\";");
    _builder.newLine();
    _builder.append("const GRAPH_PATH = \"../data/graph.json\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("document.addEventListener(\"DOMContentLoaded\", () => {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const page = document.body.dataset.page || \"overview\";");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("activateNav(page);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("loadData()");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".then(({ data, graph }) => renderPage(page, data, graph))");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".catch(error => renderError(error));");
    _builder.newLine();
    _builder.append("});");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function activateNav(page) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("document.querySelectorAll(\"[data-nav]\").forEach(link => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (link.dataset.nav === page) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("link.classList.add(\"active\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("async function loadData() {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const dataResponse = await fetch(DATA_PATH);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("if (!dataResponse.ok) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("throw new Error(\"Could not load \" + DATA_PATH);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const data = await dataResponse.json();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("let graph = null;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const graphResponse = await fetch(GRAPH_PATH);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (graphResponse.ok) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("graph = await graphResponse.json();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} catch (error) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("graph = null;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return { data, graph };");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderPage(page, data, graph) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("if (page === \"overview\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderOverview(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else if (page === \"influences\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderInfluences(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else if (page === \"requirements\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderRequirements(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else if (page === \"developers\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderDevelopers(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else if (page === \"tradeoffs\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderTradeoffs(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else if (page === \"graph\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderGraph(graph);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("renderOverview(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderOverview(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const root = rootElement();");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const counts = data.model?.counts || {};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("root.innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"row g-3 mb-4\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"Artifacts\", counts.artifacts)}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"Environmental Factors\", counts.environmentalFactors)}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"SRPs\", counts.systemResponseProperties)}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"Satisfaction Criteria\", counts.satisfactionCriteria)}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"Influences\", counts.influences)}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${metricCard(\"Analytic Influences\", counts.analyticInfluences)}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"row g-4\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"col-lg-6\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h5>Artifact propagated impact</h5>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<canvas id=\"artifactImpactChart\" height=\"220\"></canvas>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"col-lg-6\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h5>Environmental factor propagated impact</h5>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<canvas id=\"factorImpactChart\" height=\"220\"></canvas>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("renderBarChart(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"artifactImpactChart\",");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("data.metrics?.impactArtifactsPropagatedWeighted || data.metrics?.impactArtifactsPropagated || {}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("renderBarChart(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"factorImpactChart\",");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("data.metrics?.impactEnvironmentalFactorsPropagatedWeighted || data.metrics?.impactEnvironmentalFactorsPropagated || {}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderInfluences(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const rows = (data.influences || []).map(inf => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const participantNames = (inf.participants || []).map(p => p.name).join(\", \");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const functionTypes = ((inf.function || {}).representations || []).map(r => r.type).join(\", \");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const requirements = (inf.linkedRequirements || []).join(\", \");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td><strong>${escapeHtml(inf.name)}</strong></td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(inf.outputSRP)}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(participantNames)}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(functionTypes)}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(requirements)}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<h5 class=\"mb-3\">Influence list</h5>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"table-responsive\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<table class=\"table table-hover align-middle\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Influence</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Output SRP</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Participants</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Function representations</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Linked requirements</th>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<tbody>${rows}</tbody>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderRequirements(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const rows = (data.satisfactionCriteria || []).map(c => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td><strong>${escapeHtml(c.requirement)}</strong></td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(c.name)}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml((c.constrainedSRPs || []).join(\", \"))}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td><code>${escapeHtml(c.marginDefinition)}</code></td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td><span class=\"badge-soft\">${escapeHtml(c.language)}</span></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<h5 class=\"mb-3\">Requirements and satisfaction criteria</h5>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"table-responsive\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<table class=\"table table-hover align-middle\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Requirement</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Criterion</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Constrained SRPs</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Margin definition</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Language</th>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<tbody>${rows}</tbody>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderDevelopers(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const cards = (data.developerViews || []).map(view => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"col-lg-6\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"card-box h-100\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h5>${escapeHtml(view.displayName || view.id)}</h5>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<p class=\"text-muted mb-3\">Developer or subsystem-specific impact view.</p>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("          ");
    _builder.append("${listBlock(\"Owned artifacts\", view.ownedArtifacts)}");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("${listBlock(\"Influences\", view.influences)}");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("${listBlock(\"System response properties\", view.systemResponseProperties)}");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("${listBlock(\"Requirements\", view.requirements)}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"row g-4\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("${cards || emptyState(\"No developer views were generated.\")}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderTradeoffs(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const variables = collectTradeoffCandidates(data);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const rows = variables.map(v => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const status = v.hasConflict");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("? `<span class=\"badge-soft badge-danger-soft\">Trade-off</span>`");
    _builder.newLine();
    _builder.append("      ");
    _builder.append(": `<span class=\"badge-soft\">No conflict</span>`;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td><strong>${escapeHtml(v.variable)}</strong></td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(Array.from(v.benefits).join(\", \"))}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${escapeHtml(Array.from(v.prejudices).join(\", \"))}</td>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td>${status}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<h5 class=\"mb-3\">Cross-requirement trade-off candidates</h5>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<p class=\"text-muted\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("This first version uses generated dashboard data. Later we can connect it directly");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("to analytic sensitivity results.");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"table-responsive\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<table class=\"table table-hover align-middle\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Variable</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Benefits</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Prejudices</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<th>Status</th>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<tbody>${rows || `<tr><td colspan=\"4\">No trade-off candidates available.</td></tr>`}</tbody>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderGraph(graph) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("if (!graph) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rootElement().innerHTML = emptyState(\"No graph data available.\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const nodeRows = (graph.nodes || []).map(n => `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td><strong>${escapeHtml(n.id)}</strong></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(n.label)}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td><span class=\"badge-soft\">${escapeHtml(n.type)}</span></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(n.sourceModel || \"\")}</td>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const edgeRows = (graph.edges || []).map(e => `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(e.source)}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(e.target)}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(e.label || \"\")}</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>${escapeHtml(e.weight)}</td>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`).join(\"\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"row g-4\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"col-lg-6\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"card-box graph-list\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h5 class=\"mb-3\">Nodes</h5>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<table class=\"table table-hover align-middle\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>ID</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Label</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Type</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Source model</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tbody>${nodeRows}</tbody>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"col-lg-6\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"card-box graph-list\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<h5 class=\"mb-3\">Edges</h5>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<table class=\"table table-hover align-middle\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Source</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Target</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Label</th>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<th>Weight</th>");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tbody>${edgeRows}</tbody>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function metricCard(label, value) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"col-xl-2 col-md-4 col-sm-6\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"metric-card\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"metric-label\">${escapeHtml(label)}</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"metric-value\">${value ?? 0}</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function listBlock(title, values) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const items = (values || []).map(v => `<li>${escapeHtml(v)}</li>`).join(\"\");");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"mb-3\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<div class=\"fw-semibold\">${escapeHtml(title)}</div>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<ul class=\"mb-0\">${items || \"<li class=\'text-muted\'>None</li>\"}</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderBarChart(canvasId, map) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const canvas = document.getElementById(canvasId);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("if (!canvas || typeof Chart === \"undefined\") {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const labels = Object.keys(map || {});");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const values = labels.map(k => map[k]);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("new Chart(canvas, {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("type: \"bar\",");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("data: {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("labels,");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("datasets: [{");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("label: \"Impact\",");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("data: values");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("}]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("},");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("options: {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("responsive: true,");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("plugins: {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("legend: {");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("display: false");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("},");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("scales: {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("y: {");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("beginAtZero: true");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function collectTradeoffCandidates(data) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const result = [];");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const artifactMetrics = data.metrics?.impactArtifactsPropagatedWeighted || {};");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("const directMetrics = data.metrics?.impactArtifactsWeighted || {};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Object.keys(artifactMetrics).forEach(variable => {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const propagated = artifactMetrics[variable] || 0;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const direct = directMetrics[variable] || 0;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("const item = {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("variable,");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("benefits: new Set(),");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("prejudices: new Set(),");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("hasConflict: false");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (propagated > 0) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("item.benefits.add(\"Potential propagated impact\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (direct > 0 && propagated > direct) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("item.prejudices.add(\"Potential indirect impact to inspect\");");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("item.hasConflict = true;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("result.push(item);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("});");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return result;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function emptyState(message) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<p class=\"text-muted mb-0\">${escapeHtml(message)}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function renderError(error) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("rootElement().innerHTML = `");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"card-box\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<h5>Dashboard loading error</h5>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<p class=\"text-danger\">${escapeHtml(error.message || String(error))}</p>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<p class=\"text-muted mb-0\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Check that dashboard/data/dashboard-data.json was generated.");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("`;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function rootElement() {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return document.getElementById(\"dashboard-root\");");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("function escapeHtml(value) {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("if (value === null || value === undefined) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return \"\";");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("return String(value)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".replaceAll(\"&\", \"&amp;\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".replaceAll(\"<\", \"&lt;\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".replaceAll(\">\", \"&gt;\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".replaceAll(\'\"\', \"&quot;\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".replaceAll(\"\'\", \"&#039;\");");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
