/*
 * generated by Xtext 2.40.0
 */
package fr.inria.kairos.influence.serializer;

import com.google.inject.Inject;
import fr.inria.kairos.influence.metamodel.AnalyticExpressionFunction;
import fr.inria.kairos.influence.metamodel.ArtifactParticipant;
import fr.inria.kairos.influence.metamodel.CompositeInfluence;
import fr.inria.kairos.influence.metamodel.DesignArtifact;
import fr.inria.kairos.influence.metamodel.EnvironmentalFactor;
import fr.inria.kairos.influence.metamodel.EnvironmentalFactorParticipant;
import fr.inria.kairos.influence.metamodel.Influence;
import fr.inria.kairos.influence.metamodel.InfluenceFunction;
import fr.inria.kairos.influence.metamodel.InfluenceModel;
import fr.inria.kairos.influence.metamodel.MetamodelPackage;
import fr.inria.kairos.influence.metamodel.MonotonicityRow;
import fr.inria.kairos.influence.metamodel.MonotonicityTable;
import fr.inria.kairos.influence.metamodel.NaturalLanguageFunction;
import fr.inria.kairos.influence.metamodel.ParticipantImpactFunction;
import fr.inria.kairos.influence.metamodel.ParticipantRange;
import fr.inria.kairos.influence.metamodel.ParticipantRelativeImpact;
import fr.inria.kairos.influence.metamodel.RangeValue;
import fr.inria.kairos.influence.metamodel.SRPInputParticipant;
import fr.inria.kairos.influence.metamodel.SatisfactionCriterion;
import fr.inria.kairos.influence.metamodel.ScalarValue;
import fr.inria.kairos.influence.metamodel.SystemResponseProperty;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class InfluenceDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MetamodelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MetamodelPackage.ANALYTIC_EXPRESSION_FUNCTION:
				sequence_AnalyticExpressionFunction(context, (AnalyticExpressionFunction) semanticObject); 
				return; 
			case MetamodelPackage.ARTIFACT_PARTICIPANT:
				sequence_ArtifactParticipant(context, (ArtifactParticipant) semanticObject); 
				return; 
			case MetamodelPackage.COMPOSITE_INFLUENCE:
				sequence_CompositeInfluence(context, (CompositeInfluence) semanticObject); 
				return; 
			case MetamodelPackage.DESIGN_ARTIFACT:
				sequence_DesignArtifact(context, (DesignArtifact) semanticObject); 
				return; 
			case MetamodelPackage.ENVIRONMENTAL_FACTOR:
				sequence_EnvironmentalFactor(context, (EnvironmentalFactor) semanticObject); 
				return; 
			case MetamodelPackage.ENVIRONMENTAL_FACTOR_PARTICIPANT:
				sequence_EnvironmentalFactorParticipant(context, (EnvironmentalFactorParticipant) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE:
				sequence_Influence(context, (Influence) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE_FUNCTION:
				sequence_InfluenceFunction(context, (InfluenceFunction) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE_MODEL:
				sequence_InfluenceModel(context, (InfluenceModel) semanticObject); 
				return; 
			case MetamodelPackage.MONOTONICITY_ROW:
				sequence_MonotonicityRow(context, (MonotonicityRow) semanticObject); 
				return; 
			case MetamodelPackage.MONOTONICITY_TABLE:
				sequence_MonotonicityTable(context, (MonotonicityTable) semanticObject); 
				return; 
			case MetamodelPackage.NATURAL_LANGUAGE_FUNCTION:
				sequence_NaturalLanguageFunction(context, (NaturalLanguageFunction) semanticObject); 
				return; 
			case MetamodelPackage.PARTICIPANT_IMPACT_FUNCTION:
				sequence_ParticipantImpactFunction(context, (ParticipantImpactFunction) semanticObject); 
				return; 
			case MetamodelPackage.PARTICIPANT_RANGE:
				sequence_ParticipantRange(context, (ParticipantRange) semanticObject); 
				return; 
			case MetamodelPackage.PARTICIPANT_RELATIVE_IMPACT:
				sequence_ParticipantRelativeImpact(context, (ParticipantRelativeImpact) semanticObject); 
				return; 
			case MetamodelPackage.RANGE_VALUE:
				sequence_RangeValue(context, (RangeValue) semanticObject); 
				return; 
			case MetamodelPackage.SRP_INPUT_PARTICIPANT:
				sequence_SRPInputParticipant(context, (SRPInputParticipant) semanticObject); 
				return; 
			case MetamodelPackage.SATISFACTION_CRITERION:
				sequence_SatisfactionCriterion(context, (SatisfactionCriterion) semanticObject); 
				return; 
			case MetamodelPackage.SCALAR_VALUE:
				sequence_ScalarValue(context, (ScalarValue) semanticObject); 
				return; 
			case MetamodelPackage.SYSTEM_RESPONSE_PROPERTY:
				sequence_SystemResponseProperty(context, (SystemResponseProperty) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionRepresentation returns AnalyticExpressionFunction
	 *     AnalyticExpressionFunction returns AnalyticExpressionFunction
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         sourceUri=EString? 
	 *         confidence=EDouble? 
	 *         (applicabilityDomain+=ParticipantRange applicabilityDomain+=ParticipantRange*)? 
	 *         expression=EString 
	 *         expressionLanguage=LanguageType
	 *     )
	 * </pre>
	 */
	protected void sequence_AnalyticExpressionFunction(ISerializationContext context, AnalyticExpressionFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns ArtifactParticipant
	 *     ArtifactParticipant returns ArtifactParticipant
	 *
	 * Constraint:
	 *     (name=EString target=[DesignArtifact|QualifiedName] confidence=EDouble?)
	 * </pre>
	 */
	protected void sequence_ArtifactParticipant(ISerializationContext context, ArtifactParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractInfluence returns CompositeInfluence
	 *     CompositeInfluence returns CompositeInfluence
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         internalInfluences+=[AbstractInfluence|QualifiedName] 
	 *         internalInfluences+=[AbstractInfluence|QualifiedName]* 
	 *         ownedInfluenceFunction=InfluenceFunction
	 *     )
	 * </pre>
	 */
	protected void sequence_CompositeInfluence(ISerializationContext context, CompositeInfluence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DesignArtifact returns DesignArtifact
	 *
	 * Constraint:
	 *     (name=EString ref=[EObject|QualifiedName] changeability=EDouble?)
	 * </pre>
	 */
	protected void sequence_DesignArtifact(ISerializationContext context, DesignArtifact semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns EnvironmentalFactorParticipant
	 *     EnvironmentalFactorParticipant returns EnvironmentalFactorParticipant
	 *
	 * Constraint:
	 *     (name=EString target=[EnvironmentalFactor|QualifiedName] confidence=EDouble? admissibleSpace=ValueSpec?)
	 * </pre>
	 */
	protected void sequence_EnvironmentalFactorParticipant(ISerializationContext context, EnvironmentalFactorParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnvironmentalFactor returns EnvironmentalFactor
	 *
	 * Constraint:
	 *     (name=EString description=EString flexibility=EDouble?)
	 * </pre>
	 */
	protected void sequence_EnvironmentalFactor(ISerializationContext context, EnvironmentalFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InfluenceFunction returns InfluenceFunction
	 *
	 * Constraint:
	 *     (name=EString representations+=FunctionRepresentation representations+=FunctionRepresentation*)
	 * </pre>
	 */
	protected void sequence_InfluenceFunction(ISerializationContext context, InfluenceFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InfluenceModel returns InfluenceModel
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (
	 *             (
	 *                 ownedSRPs+=SystemResponseProperty | 
	 *                 ownedInfluences+=AbstractInfluence | 
	 *                 ownedSatisfactionCriteria+=SatisfactionCriterion | 
	 *                 ownedEnvironmentalFactors+=EnvironmentalFactor | 
	 *                 ownedArtifacts+=DesignArtifact
	 *             ) 
	 *             ownedSRPs+=SystemResponseProperty? 
	 *             (
	 *                 (
	 *                     ownedInfluences+=AbstractInfluence | 
	 *                     ownedSatisfactionCriteria+=SatisfactionCriterion | 
	 *                     ownedEnvironmentalFactors+=EnvironmentalFactor | 
	 *                     ownedArtifacts+=DesignArtifact
	 *                 )? 
	 *                 ownedSRPs+=SystemResponseProperty?
	 *             )*
	 *         )?
	 *     )
	 * </pre>
	 */
	protected void sequence_InfluenceModel(ISerializationContext context, InfluenceModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractInfluence returns Influence
	 *     Influence returns Influence
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         ownedParticipants+=Participant 
	 *         ownedParticipants+=Participant* 
	 *         ownedInfluenceFunction=InfluenceFunction 
	 *         outputSRP=[SystemResponseProperty|QualifiedName]
	 *     )
	 * </pre>
	 */
	protected void sequence_Influence(ISerializationContext context, Influence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MonotonicityRow returns MonotonicityRow
	 *
	 * Constraint:
	 *     (
	 *         (condition+=ParticipantRange condition+=ParticipantRange*)? 
	 *         variedParticipant=[Participant|QualifiedName] 
	 *         output=[SystemResponseProperty|QualifiedName] 
	 *         trend=TrendType
	 *     )
	 * </pre>
	 */
	protected void sequence_MonotonicityRow(ISerializationContext context, MonotonicityRow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionRepresentation returns MonotonicityTable
	 *     MonotonicityTable returns MonotonicityTable
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         sourceUri=EString? 
	 *         confidence=EDouble? 
	 *         (applicabilityDomain+=ParticipantRange applicabilityDomain+=ParticipantRange*)? 
	 *         tableRows+=MonotonicityRow 
	 *         tableRows+=MonotonicityRow*
	 *     )
	 * </pre>
	 */
	protected void sequence_MonotonicityTable(ISerializationContext context, MonotonicityTable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionRepresentation returns NaturalLanguageFunction
	 *     NaturalLanguageFunction returns NaturalLanguageFunction
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         sourceUri=EString? 
	 *         confidence=EDouble? 
	 *         (applicabilityDomain+=ParticipantRange applicabilityDomain+=ParticipantRange*)? 
	 *         definition=EString
	 *     )
	 * </pre>
	 */
	protected void sequence_NaturalLanguageFunction(ISerializationContext context, NaturalLanguageFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionRepresentation returns ParticipantImpactFunction
	 *     ParticipantImpactFunction returns ParticipantImpactFunction
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         sourceUri=EString? 
	 *         confidence=EDouble? 
	 *         (applicabilityDomain+=ParticipantRange applicabilityDomain+=ParticipantRange*)? 
	 *         participantContribution+=ParticipantRelativeImpact 
	 *         participantContribution+=ParticipantRelativeImpact*
	 *     )
	 * </pre>
	 */
	protected void sequence_ParticipantImpactFunction(ISerializationContext context, ParticipantImpactFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ParticipantRange returns ParticipantRange
	 *
	 * Constraint:
	 *     (name=EString participant=[Participant|QualifiedName] value=ValueSpec)
	 * </pre>
	 */
	protected void sequence_ParticipantRange(ISerializationContext context, ParticipantRange semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.PARTICIPANT_RANGE__PARTICIPANT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.PARTICIPANT_RANGE__PARTICIPANT));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.PARTICIPANT_RANGE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.PARTICIPANT_RANGE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParticipantRangeAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getParticipantRangeAccess().getParticipantParticipantQualifiedNameParserRuleCall_3_0_1(), semanticObject.eGet(MetamodelPackage.Literals.PARTICIPANT_RANGE__PARTICIPANT, false));
		feeder.accept(grammarAccess.getParticipantRangeAccess().getValueValueSpecParserRuleCall_5_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ParticipantRelativeImpact returns ParticipantRelativeImpact
	 *
	 * Constraint:
	 *     (participant=[Participant|QualifiedName] importance=EDouble direction=TrendType? rationale=EString?)
	 * </pre>
	 */
	protected void sequence_ParticipantRelativeImpact(ISerializationContext context, ParticipantRelativeImpact semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueSpec returns RangeValue
	 *     RangeValue returns RangeValue
	 *
	 * Constraint:
	 *     (
	 *         lower=EDouble 
	 *         upper=EDouble 
	 *         nominal=EDouble? 
	 *         step=EDouble? 
	 *         unit=EString? 
	 *         inclusiveLower=EBoolean? 
	 *         inclusiveUpper=EBoolean?
	 *     )
	 * </pre>
	 */
	protected void sequence_RangeValue(ISerializationContext context, RangeValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns SRPInputParticipant
	 *     SRPInputParticipant returns SRPInputParticipant
	 *
	 * Constraint:
	 *     (name=EString target=[SystemResponseProperty|QualifiedName] confidence=EDouble?)
	 * </pre>
	 */
	protected void sequence_SRPInputParticipant(ISerializationContext context, SRPInputParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SatisfactionCriterion returns SatisfactionCriterion
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         requirementRef=[EObject|QualifiedName] 
	 *         constrainedSRPs+=[SystemResponseProperty|QualifiedName] 
	 *         constrainedSRPs+=[SystemResponseProperty|QualifiedName]* 
	 *         marginDefinition=EString 
	 *         language=LanguageType
	 *     )
	 * </pre>
	 */
	protected void sequence_SatisfactionCriterion(ISerializationContext context, SatisfactionCriterion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueSpec returns ScalarValue
	 *     ScalarValue returns ScalarValue
	 *
	 * Constraint:
	 *     (value=EDouble unit=EString?)
	 * </pre>
	 */
	protected void sequence_ScalarValue(ISerializationContext context, ScalarValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SystemResponseProperty returns SystemResponseProperty
	 *
	 * Constraint:
	 *     (name=EString description=EString)
	 * </pre>
	 */
	protected void sequence_SystemResponseProperty(ISerializationContext context, SystemResponseProperty semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.SYSTEM_RESPONSE_PROPERTY__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.SYSTEM_RESPONSE_PROPERTY__DESCRIPTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSystemResponsePropertyAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSystemResponsePropertyAccess().getDescriptionEStringParserRuleCall_4_0(), semanticObject.getDescription());
		feeder.finish();
	}
	
	
}
