/*
 * generated by Xtext 2.39.0
 */
package fr.inria.kairos.influence.serializer;

import com.google.inject.Inject;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class InfluenceDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected InfluenceDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_CompositeInfluence_AsteriskAsteriskNumberSignKeyword_6_q;
	protected AbstractElementAlias match_Influence_AsteriskAsteriskNumberSignKeyword_5_q;
	protected AbstractElementAlias match_Metadata___CommaKeyword_1_0_1_or_WithKeyword_1_0_0__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (InfluenceDSLGrammarAccess) access;
		match_CompositeInfluence_AsteriskAsteriskNumberSignKeyword_6_q = new TokenAlias(false, true, grammarAccess.getCompositeInfluenceAccess().getAsteriskAsteriskNumberSignKeyword_6());
		match_Influence_AsteriskAsteriskNumberSignKeyword_5_q = new TokenAlias(false, true, grammarAccess.getInfluenceAccess().getAsteriskAsteriskNumberSignKeyword_5());
		match_Metadata___CommaKeyword_1_0_1_or_WithKeyword_1_0_0__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getMetadataAccess().getCommaKeyword_1_0_1()), new TokenAlias(false, false, grammarAccess.getMetadataAccess().getWithKeyword_1_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_CompositeInfluence_AsteriskAsteriskNumberSignKeyword_6_q.equals(syntax))
				emit_CompositeInfluence_AsteriskAsteriskNumberSignKeyword_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Influence_AsteriskAsteriskNumberSignKeyword_5_q.equals(syntax))
				emit_Influence_AsteriskAsteriskNumberSignKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Metadata___CommaKeyword_1_0_1_or_WithKeyword_1_0_0__q.equals(syntax))
				emit_Metadata___CommaKeyword_1_0_1_or_WithKeyword_1_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '**#'?
	 *
	 * This ambiguous syntax occurs at:
	 *     description+=EString (ambiguity) 'encapsulate' internalInfluences+=[AbstractInfluence|EString]
	 *     description+=EString (ambiguity) 'encapsulate' ownedFunction=CompositeFunction
	 
	 * </pre>
	 */
	protected void emit_CompositeInfluence_AsteriskAsteriskNumberSignKeyword_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '**#'?
	 *
	 * This ambiguous syntax occurs at:
	 *     description+=EString (ambiguity) 'originators' ':' 'artifact' originatorArtifact+=[DesignArtifact|ID]
	 *     description+=EString (ambiguity) 'originators' ':' 'phenomena' originatorPhenomena+=[PhysicalPhenomena|EString]
	 *     description+=EString (ambiguity) 'originators' ':' 'system' 'response' originatorSystemResponse+=[SystemResponse|EString]
	 
	 * </pre>
	 */
	protected void emit_Influence_AsteriskAsteriskNumberSignKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('with' | ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     element=[DesignArtifact|ID] (ambiguity) ',' 'confidence' '=' confidence=DOUBLE
	 *     element=[DesignArtifact|ID] (ambiguity) ',' 'strength' '=' strength=DOUBLE
	 *     element=[DesignArtifact|ID] (ambiguity) 'likelihood' '=' likelihood=DOUBLE
	 *     element=[DesignArtifact|ID] (ambiguity) (rule end)
	 *     element=[PhysicalPhenomena|EString] (ambiguity) ',' 'confidence' '=' confidence=DOUBLE
	 *     element=[PhysicalPhenomena|EString] (ambiguity) ',' 'strength' '=' strength=DOUBLE
	 *     element=[PhysicalPhenomena|EString] (ambiguity) 'likelihood' '=' likelihood=DOUBLE
	 *     element=[PhysicalPhenomena|EString] (ambiguity) (rule end)
	 *     element=[SystemResponse|EString] (ambiguity) ',' 'confidence' '=' confidence=DOUBLE
	 *     element=[SystemResponse|EString] (ambiguity) ',' 'strength' '=' strength=DOUBLE
	 *     element=[SystemResponse|EString] (ambiguity) 'likelihood' '=' likelihood=DOUBLE
	 *     element=[SystemResponse|EString] (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Metadata___CommaKeyword_1_0_1_or_WithKeyword_1_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
