/*
 * generated by Xtext 2.40.0
 */
package fr.inria.kairos.influence.serializer;

import com.google.inject.Inject;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class InfluenceDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected InfluenceDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_InfluenceModel_CommaKeyword_3_2_q;
	protected AbstractElementAlias match_Influence_AsteriskAsteriskNumberSignKeyword_5_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (InfluenceDSLGrammarAccess) access;
		match_InfluenceModel_CommaKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getInfluenceModelAccess().getCommaKeyword_3_2());
		match_Influence_AsteriskAsteriskNumberSignKeyword_5_q = new TokenAlias(false, true, grammarAccess.getInfluenceAccess().getAsteriskAsteriskNumberSignKeyword_5());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_InfluenceModel_CommaKeyword_3_2_q.equals(syntax))
				emit_InfluenceModel_CommaKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Influence_AsteriskAsteriskNumberSignKeyword_5_q.equals(syntax))
				emit_Influence_AsteriskAsteriskNumberSignKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     ownedArtifacts+=DesignArtifact (ambiguity) (rule end)
	 *     ownedEnvironmentalFactors+=EnvironmentalFactor (ambiguity) (rule end)
	 *     ownedInfluences+=AbstractInfluence (ambiguity) (rule end)
	 *     ownedRequirements+=Requirement (ambiguity) (rule end)
	 *     ownedSRPs+=SystemResponseProperty (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_InfluenceModel_CommaKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '**#'?
	 *
	 * This ambiguous syntax occurs at:
	 *     description+=EString (ambiguity) 'participants' ':' ownedParticipants+=Participant
	 
	 * </pre>
	 */
	protected void emit_Influence_AsteriskAsteriskNumberSignKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
