/*
 * generated by Xtext 2.40.0
 */
package fr.inria.kairos.influence.serializer;

import com.google.inject.Inject;
import fr.inria.kairos.influence.metamodel.ArtifactParticipant;
import fr.inria.kairos.influence.metamodel.CompositeInfluence;
import fr.inria.kairos.influence.metamodel.DesignArtifact;
import fr.inria.kairos.influence.metamodel.EnvironmentalFactor;
import fr.inria.kairos.influence.metamodel.EnvironmentalFactorParticipant;
import fr.inria.kairos.influence.metamodel.Influence;
import fr.inria.kairos.influence.metamodel.InfluenceFunction;
import fr.inria.kairos.influence.metamodel.InfluenceModel;
import fr.inria.kairos.influence.metamodel.MetamodelPackage;
import fr.inria.kairos.influence.metamodel.Requirement;
import fr.inria.kairos.influence.metamodel.SRPInputParticipant;
import fr.inria.kairos.influence.metamodel.SystemResponseProperty;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class InfluenceDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MetamodelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MetamodelPackage.ARTIFACT_PARTICIPANT:
				sequence_ArtifactParticipant(context, (ArtifactParticipant) semanticObject); 
				return; 
			case MetamodelPackage.COMPOSITE_INFLUENCE:
				sequence_CompositeInfluence(context, (CompositeInfluence) semanticObject); 
				return; 
			case MetamodelPackage.DESIGN_ARTIFACT:
				sequence_DesignArtifact(context, (DesignArtifact) semanticObject); 
				return; 
			case MetamodelPackage.ENVIRONMENTAL_FACTOR:
				sequence_EnvironmentalFactor(context, (EnvironmentalFactor) semanticObject); 
				return; 
			case MetamodelPackage.ENVIRONMENTAL_FACTOR_PARTICIPANT:
				sequence_EnvironmentalFactorParticipant(context, (EnvironmentalFactorParticipant) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE:
				sequence_Influence(context, (Influence) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE_FUNCTION:
				sequence_InfluenceFunction(context, (InfluenceFunction) semanticObject); 
				return; 
			case MetamodelPackage.INFLUENCE_MODEL:
				sequence_InfluenceModel(context, (InfluenceModel) semanticObject); 
				return; 
			case MetamodelPackage.REQUIREMENT:
				sequence_Requirement(context, (Requirement) semanticObject); 
				return; 
			case MetamodelPackage.SRP_INPUT_PARTICIPANT:
				sequence_SRPInputParticipant(context, (SRPInputParticipant) semanticObject); 
				return; 
			case MetamodelPackage.SYSTEM_RESPONSE_PROPERTY:
				sequence_SystemResponseProperty(context, (SystemResponseProperty) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns ArtifactParticipant
	 *     ArtifactParticipant returns ArtifactParticipant
	 *
	 * Constraint:
	 *     (target=[DesignArtifact|EString] weight=EDouble? likelihood=EDouble? confidence=EDouble?)
	 * </pre>
	 */
	protected void sequence_ArtifactParticipant(ISerializationContext context, ArtifactParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractInfluence returns CompositeInfluence
	 *     CompositeInfluence returns CompositeInfluence
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description+=EString 
	 *         description+=EString* 
	 *         internalInfluences+=[AbstractInfluence|EString] 
	 *         internalInfluences+=[AbstractInfluence|EString]* 
	 *         ownedInfluenceFunction=InfluenceFunction
	 *     )
	 * </pre>
	 */
	protected void sequence_CompositeInfluence(ISerializationContext context, CompositeInfluence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DesignArtifact returns DesignArtifact
	 *
	 * Constraint:
	 *     (name=EString ref=[EObject|EString] changeability=EDouble?)
	 * </pre>
	 */
	protected void sequence_DesignArtifact(ISerializationContext context, DesignArtifact semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns EnvironmentalFactorParticipant
	 *     EnvironmentalFactorParticipant returns EnvironmentalFactorParticipant
	 *
	 * Constraint:
	 *     (target=[EnvironmentalFactor|QualifiedName] weight=EDouble? likelihood=EDouble? confidence=EDouble?)
	 * </pre>
	 */
	protected void sequence_EnvironmentalFactorParticipant(ISerializationContext context, EnvironmentalFactorParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnvironmentalFactor returns EnvironmentalFactor
	 *
	 * Constraint:
	 *     (name=EString description=EString flexibility=EDouble? value=EDouble? unit=EString?)
	 * </pre>
	 */
	protected void sequence_EnvironmentalFactor(ISerializationContext context, EnvironmentalFactor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InfluenceFunction returns InfluenceFunction
	 *
	 * Constraint:
	 *     (name=EString definition=EString returnType=ValueType language=LanguageType)
	 * </pre>
	 */
	protected void sequence_InfluenceFunction(ISerializationContext context, InfluenceFunction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__DEFINITION));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__RETURN_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__RETURN_TYPE));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__LANGUAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.INFLUENCE_FUNCTION__LANGUAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInfluenceFunctionAccess().getNameEStringParserRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getInfluenceFunctionAccess().getDefinitionEStringParserRuleCall_3_0(), semanticObject.getDefinition());
		feeder.accept(grammarAccess.getInfluenceFunctionAccess().getReturnTypeValueTypeEnumRuleCall_5_0(), semanticObject.getReturnType());
		feeder.accept(grammarAccess.getInfluenceFunctionAccess().getLanguageLanguageTypeEnumRuleCall_7_0(), semanticObject.getLanguage());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InfluenceModel returns InfluenceModel
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (
	 *             (
	 *                 ownedSRPs+=SystemResponseProperty | 
	 *                 ownedInfluences+=AbstractInfluence | 
	 *                 ownedRequirements+=Requirement | 
	 *                 ownedEnvironmentalFactors+=EnvironmentalFactor | 
	 *                 ownedArtifacts+=DesignArtifact
	 *             ) 
	 *             ownedSRPs+=SystemResponseProperty? 
	 *             (
	 *                 (ownedInfluences+=AbstractInfluence | ownedRequirements+=Requirement | ownedEnvironmentalFactors+=EnvironmentalFactor | ownedArtifacts+=DesignArtifact)? 
	 *                 ownedSRPs+=SystemResponseProperty?
	 *             )*
	 *         )?
	 *     )
	 * </pre>
	 */
	protected void sequence_InfluenceModel(ISerializationContext context, InfluenceModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractInfluence returns Influence
	 *     Influence returns Influence
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description+=EString 
	 *         description+=EString* 
	 *         ownedParticipants+=Participant 
	 *         ownedParticipants+=Participant* 
	 *         ownedInfluenceFunction=InfluenceFunction 
	 *         outputSRP=[SystemResponseProperty|QualifiedName]
	 *     )
	 * </pre>
	 */
	protected void sequence_Influence(ISerializationContext context, Influence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Requirement returns Requirement
	 *
	 * Constraint:
	 *     (name=EString description=EString satisfaction=EString language=LanguageType)
	 * </pre>
	 */
	protected void sequence_Requirement(ISerializationContext context, Requirement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.REQUIREMENT__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.REQUIREMENT__DESCRIPTION));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.REQUIREMENT__SATISFACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.REQUIREMENT__SATISFACTION));
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.REQUIREMENT__LANGUAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.REQUIREMENT__LANGUAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRequirementAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRequirementAccess().getDescriptionEStringParserRuleCall_3_0(), semanticObject.getDescription());
		feeder.accept(grammarAccess.getRequirementAccess().getSatisfactionEStringParserRuleCall_6_0(), semanticObject.getSatisfaction());
		feeder.accept(grammarAccess.getRequirementAccess().getLanguageLanguageTypeEnumRuleCall_8_0(), semanticObject.getLanguage());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Participant returns SRPInputParticipant
	 *     SRPInputParticipant returns SRPInputParticipant
	 *
	 * Constraint:
	 *     (target=[SystemResponseProperty|QualifiedName] weight=EDouble? likelihood=EDouble? confidence=EDouble?)
	 * </pre>
	 */
	protected void sequence_SRPInputParticipant(ISerializationContext context, SRPInputParticipant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SystemResponseProperty returns SystemResponseProperty
	 *
	 * Constraint:
	 *     (name=EString description=EString (constrainedBy+=[Requirement|QualifiedName] constrainedBy+=[Requirement|QualifiedName]*)?)
	 * </pre>
	 */
	protected void sequence_SystemResponseProperty(ISerializationContext context, SystemResponseProperty semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
