/*
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.kairos.influence.ide.contentassist.antlr.internal.InternalInfluenceDSLParser;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class InfluenceDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(InfluenceDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, InfluenceDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInfluenceModelAccess().getAlternatives_3(), "rule__InfluenceModel__Alternatives_3");
			builder.put(grammarAccess.getAbstractInfluenceAccess().getAlternatives(), "rule__AbstractInfluence__Alternatives");
			builder.put(grammarAccess.getInfluenceAccess().getAlternatives_8(), "rule__Influence__Alternatives_8");
			builder.put(grammarAccess.getInfluenceAccess().getAlternatives_9_1(), "rule__Influence__Alternatives_9_1");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getInfluenceModelAccess().getGroup(), "rule__InfluenceModel__Group__0");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getGroup(), "rule__CompositeInfluence__Group__0");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getGroup_5(), "rule__CompositeInfluence__Group_5__0");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getGroup_11(), "rule__CompositeInfluence__Group_11__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup(), "rule__Influence__Group__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_4(), "rule__Influence__Group_4__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_8_0(), "rule__Influence__Group_8_0__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_8_1(), "rule__Influence__Group_8_1__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_8_2(), "rule__Influence__Group_8_2__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_9(), "rule__Influence__Group_9__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_9_1_0(), "rule__Influence__Group_9_1_0__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_9_1_1(), "rule__Influence__Group_9_1_1__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_9_1_2(), "rule__Influence__Group_9_1_2__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_12(), "rule__Influence__Group_12__0");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getGroup(), "rule__PhysicalPhenomena__Group__0");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getGroup_2(), "rule__PhysicalPhenomena__Group_2__0");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getGroup_2_2(), "rule__PhysicalPhenomena__Group_2_2__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup(), "rule__RequirementSatisfaction__Group__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup_6(), "rule__RequirementSatisfaction__Group_6__0");
			builder.put(grammarAccess.getDesignArtifactAccess().getGroup(), "rule__DesignArtifact__Group__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup(), "rule__SystemResponse__Group__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup_4(), "rule__SystemResponse__Group_4__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup_4_3(), "rule__SystemResponse__Group_4_3__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
			builder.put(grammarAccess.getInfluenceModelAccess().getNameAssignment_2(), "rule__InfluenceModel__NameAssignment_2");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedArtifactsAssignment_3_0(), "rule__InfluenceModel__OwnedArtifactsAssignment_3_0");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedRequirementsAssignment_3_1(), "rule__InfluenceModel__OwnedRequirementsAssignment_3_1");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedPhysicalPhenomenaAssignment_3_2(), "rule__InfluenceModel__OwnedPhysicalPhenomenaAssignment_3_2");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedInfluencesAssignment_3_3(), "rule__InfluenceModel__OwnedInfluencesAssignment_3_3");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getNameAssignment_2(), "rule__CompositeInfluence__NameAssignment_2");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getDescriptionAssignment_4(), "rule__CompositeInfluence__DescriptionAssignment_4");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getDescriptionAssignment_5_1(), "rule__CompositeInfluence__DescriptionAssignment_5_1");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getInternalInfluencesAssignment_8(), "rule__CompositeInfluence__InternalInfluencesAssignment_8");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getAffectsAssignment_10(), "rule__CompositeInfluence__AffectsAssignment_10");
			builder.put(grammarAccess.getCompositeInfluenceAccess().getAffectsAssignment_11_1(), "rule__CompositeInfluence__AffectsAssignment_11_1");
			builder.put(grammarAccess.getInfluenceAccess().getNameAssignment_1(), "rule__Influence__NameAssignment_1");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_3(), "rule__Influence__DescriptionAssignment_3");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_4_1(), "rule__Influence__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorArtifactAssignment_8_0_1(), "rule__Influence__OriginatorArtifactAssignment_8_0_1");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorPhenomenaAssignment_8_1_1(), "rule__Influence__OriginatorPhenomenaAssignment_8_1_1");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorSystemResponseAssignment_8_2_2(), "rule__Influence__OriginatorSystemResponseAssignment_8_2_2");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorArtifactAssignment_9_1_0_1(), "rule__Influence__OriginatorArtifactAssignment_9_1_0_1");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorPhenomenaAssignment_9_1_1_1(), "rule__Influence__OriginatorPhenomenaAssignment_9_1_1_1");
			builder.put(grammarAccess.getInfluenceAccess().getOriginatorSystemResponseAssignment_9_1_2_2(), "rule__Influence__OriginatorSystemResponseAssignment_9_1_2_2");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_11(), "rule__Influence__AffectsAssignment_11");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_12_1(), "rule__Influence__AffectsAssignment_12_1");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getNameAssignment_1(), "rule__PhysicalPhenomena__NameAssignment_1");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getDescriptionAssignment_2_1(), "rule__PhysicalPhenomena__DescriptionAssignment_2_1");
			builder.put(grammarAccess.getPhysicalPhenomenaAccess().getDescriptionAssignment_2_2_1(), "rule__PhysicalPhenomena__DescriptionAssignment_2_2_1");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getNameAssignment_1(), "rule__RequirementSatisfaction__NameAssignment_1");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_5(), "rule__RequirementSatisfaction__SatisfactionAssignment_5");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_6_1(), "rule__RequirementSatisfaction__SatisfactionAssignment_6_1");
			builder.put(grammarAccess.getDesignArtifactAccess().getNameAssignment_2(), "rule__DesignArtifact__NameAssignment_2");
			builder.put(grammarAccess.getDesignArtifactAccess().getRefAssignment_4(), "rule__DesignArtifact__RefAssignment_4");
			builder.put(grammarAccess.getSystemResponseAccess().getNameAssignment_3(), "rule__SystemResponse__NameAssignment_3");
			builder.put(grammarAccess.getSystemResponseAccess().getUsedInAssignment_4_2(), "rule__SystemResponse__UsedInAssignment_4_2");
			builder.put(grammarAccess.getSystemResponseAccess().getUsedInAssignment_4_3_1(), "rule__SystemResponse__UsedInAssignment_4_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;

	@Override
	protected InternalInfluenceDSLParser createParser() {
		InternalInfluenceDSLParser result = new InternalInfluenceDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public InfluenceDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InfluenceDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
