/*
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.kairos.influence.ide.contentassist.antlr.internal.InternalInfluenceDSLParser;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class InfluenceDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(InfluenceDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, InfluenceDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInfluenceModelAccess().getAlternatives_3(), "rule__InfluenceModel__Alternatives_3");
			builder.put(grammarAccess.getCyberPhysicalPhenomenaAccess().getAlternatives(), "rule__CyberPhysicalPhenomena__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getInfluenceModelAccess().getGroup(), "rule__InfluenceModel__Group__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup(), "rule__MultiPhenomenon__Group__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_3(), "rule__MultiPhenomenon__Group_3__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_3_2(), "rule__MultiPhenomenon__Group_3_2__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_4(), "rule__MultiPhenomenon__Group_4__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_4_2(), "rule__MultiPhenomenon__Group_4_2__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup(), "rule__SimplePhenomenon__Group__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup_3(), "rule__SimplePhenomenon__Group_3__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup_3_2(), "rule__SimplePhenomenon__Group_3_2__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup(), "rule__Influence__Group__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_2(), "rule__Influence__Group_2__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_8(), "rule__Influence__Group_8__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_13(), "rule__Influence__Group_13__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_16(), "rule__Influence__Group_16__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_20(), "rule__Influence__Group_20__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_25(), "rule__Influence__Group_25__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_33(), "rule__Influence__Group_33__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup(), "rule__RequirementSatisfaction__Group__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup_10(), "rule__RequirementSatisfaction__Group_10__0");
			builder.put(grammarAccess.getArtifactAccess().getGroup(), "rule__Artifact__Group__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup(), "rule__SystemResponse__Group__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup_3(), "rule__SystemResponse__Group_3__0");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getGroup(), "rule__EmergentBehavior__Group__0");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getGroup_3(), "rule__EmergentBehavior__Group_3__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
			builder.put(grammarAccess.getInfluenceModelAccess().getNameAssignment_2(), "rule__InfluenceModel__NameAssignment_2");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedArtifactsAssignment_3_0(), "rule__InfluenceModel__OwnedArtifactsAssignment_3_0");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedRequirementSatisfactionAssignment_3_1(), "rule__InfluenceModel__OwnedRequirementSatisfactionAssignment_3_1");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedCyberPhysicalPhenomenaAssignment_3_2(), "rule__InfluenceModel__OwnedCyberPhysicalPhenomenaAssignment_3_2");
			builder.put(grammarAccess.getInfluenceModelAccess().getOwnedInfluencesAssignment_3_3(), "rule__InfluenceModel__OwnedInfluencesAssignment_3_3");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getNameAssignment_2(), "rule__MultiPhenomenon__NameAssignment_2");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getAggregationOfAssignment_3_1(), "rule__MultiPhenomenon__AggregationOfAssignment_3_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getAggregationOfAssignment_3_2_1(), "rule__MultiPhenomenon__AggregationOfAssignment_3_2_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getConfigurationAssignment_4_1(), "rule__MultiPhenomenon__ConfigurationAssignment_4_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getConfigurationAssignment_4_2_1(), "rule__MultiPhenomenon__ConfigurationAssignment_4_2_1");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getNameAssignment_2(), "rule__SimplePhenomenon__NameAssignment_2");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getConfigurationAssignment_3_1(), "rule__SimplePhenomenon__ConfigurationAssignment_3_1");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getConfigurationAssignment_3_2_1(), "rule__SimplePhenomenon__ConfigurationAssignment_3_2_1");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_1(), "rule__Influence__DescriptionAssignment_1");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_2_1(), "rule__Influence__DescriptionAssignment_2_1");
			builder.put(grammarAccess.getInfluenceAccess().getNameAssignment_5(), "rule__Influence__NameAssignment_5");
			builder.put(grammarAccess.getInfluenceAccess().getSourceArtifactAssignment_7(), "rule__Influence__SourceArtifactAssignment_7");
			builder.put(grammarAccess.getInfluenceAccess().getSourceArtifactAssignment_8_1(), "rule__Influence__SourceArtifactAssignment_8_1");
			builder.put(grammarAccess.getInfluenceAccess().getSourcePhenomenaAssignment_12(), "rule__Influence__SourcePhenomenaAssignment_12");
			builder.put(grammarAccess.getInfluenceAccess().getSourcePhenomenaAssignment_13_1(), "rule__Influence__SourcePhenomenaAssignment_13_1");
			builder.put(grammarAccess.getInfluenceAccess().getProducesAssignment_15(), "rule__Influence__ProducesAssignment_15");
			builder.put(grammarAccess.getInfluenceAccess().getProducesAssignment_16_1(), "rule__Influence__ProducesAssignment_16_1");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_19(), "rule__Influence__AffectsAssignment_19");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_20_1(), "rule__Influence__AffectsAssignment_20_1");
			builder.put(grammarAccess.getInfluenceAccess().getEvaluatedByAssignment_24(), "rule__Influence__EvaluatedByAssignment_24");
			builder.put(grammarAccess.getInfluenceAccess().getEvaluatedByAssignment_25_1(), "rule__Influence__EvaluatedByAssignment_25_1");
			builder.put(grammarAccess.getInfluenceAccess().getTargetArtifactAssignment_32(), "rule__Influence__TargetArtifactAssignment_32");
			builder.put(grammarAccess.getInfluenceAccess().getTargetArtifactAssignment_33_1(), "rule__Influence__TargetArtifactAssignment_33_1");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getNameAssignment_2(), "rule__RequirementSatisfaction__NameAssignment_2");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getConcerningRequirementAssignment_6(), "rule__RequirementSatisfaction__ConcerningRequirementAssignment_6");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_9(), "rule__RequirementSatisfaction__SatisfactionAssignment_9");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_10_1(), "rule__RequirementSatisfaction__SatisfactionAssignment_10_1");
			builder.put(grammarAccess.getArtifactAccess().getNameAssignment_2(), "rule__Artifact__NameAssignment_2");
			builder.put(grammarAccess.getArtifactAccess().getRefAssignment_4(), "rule__Artifact__RefAssignment_4");
			builder.put(grammarAccess.getSystemResponseAccess().getObservationAssignment_3_2(), "rule__SystemResponse__ObservationAssignment_3_2");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getDescriptionAssignment_3_2(), "rule__EmergentBehavior__DescriptionAssignment_3_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;

	@Override
	protected InternalInfluenceDSLParser createParser() {
		InternalInfluenceDSLParser result = new InternalInfluenceDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public InfluenceDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InfluenceDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
