/*
 * generated by Xtext 2.34.0
 */
package fr.inria.kairos.influence.tests

import com.google.inject.Inject
import fr.inria.kairos.influence.metamodel.InfluenceModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(InfluenceDSLInjectorProvider)
class InfluenceDSLParsingTest {
	@Inject
	ParseHelper<InfluenceModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
