<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="http://kairos.inria.fr/influences" nsPrefix="metamodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfluenceModel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInfluences" upperBound="-1"
        eType="#//AbstractInfluence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEnvironmentalFactors"
        upperBound="-1" eType="#//EnvironmentalFactor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedArtifacts" upperBound="-1"
        eType="#//DesignArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSRPs" upperBound="-1"
        eType="#//SystemResponseProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSatisfactionCriteria"
        upperBound="-1" eType="#//SatisfactionCriterion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInfluence" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Influence" eSuperTypes="#//AbstractInfluence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ParticipationPattern"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ParticipationPattern" value="&#xA;&#x9;&#x9;&#x9;self.ownedParticipants->exists(p | p.oclIsKindOf(ArtifactParticipant)) and &#xA;&#x9;&#x9;&#x9;(self.ownedParticipants->exists(p | p.oclIsKindOf(EnvironmentalFactorParticipant)))&#xA;&#x9;&#x9;&#x9;or self.ownedParticipants->exists(p |p.oclIsKindOf(SRPInputParticipant))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInfluenceFunction"
        lowerBound="1" eType="#//InfluenceFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParticipants" lowerBound="1"
        upperBound="-1" eType="#//Participant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputSRP" lowerBound="1"
        eType="#//SystemResponseProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SRPInputParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SystemResponseProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//DesignArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalFactorParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//EnvironmentalFactor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admissibleSpace" eType="#//ValueSpec"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SatisfactionCriterion" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginDefinition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedSRPs" upperBound="-1"
        eType="#//SystemResponseProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeInfluence" eSuperTypes="#//AbstractInfluence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalInfluences" lowerBound="2"
        upperBound="-1" eType="#//AbstractInfluence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInfluenceFunction"
        lowerBound="1" eType="#//InfluenceFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignArtifact" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemResponseProperty" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalFactor" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfluenceFunction" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="#//FunctionRepresentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageType">
    <eLiterals name="NaturalLanguage"/>
    <eLiterals name="JavaNumericExpression" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantRange" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ValueSpec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" eType="#//Participant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpec" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarValue" eSuperTypes="#//ValueSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeValue" eSuperTypes="#//ValueSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nominal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusiveLower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusiveUpper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionRepresentation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicabilityDomain" upperBound="-1"
        eType="#//ParticipantRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NaturalLanguageFunction" eSuperTypes="#//FunctionRepresentation #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantImpactFunction" eSuperTypes="#//FunctionRepresentation #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantContribution"
        upperBound="-1" eType="#//ParticipantRelativeImpact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantRelativeImpact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//TrendType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalyticExpressionFunction" eSuperTypes="#//FunctionRepresentation #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionLanguage" eType="#//LanguageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonotonicityTable" eSuperTypes="#//FunctionRepresentation #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableRows" lowerBound="1"
        upperBound="-1" eType="#//MonotonicityRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonotonicityRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" upperBound="-1"
        eType="#//ParticipantRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trend" eType="#//TrendType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variedParticipant" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//SystemResponseProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TrendType">
    <eLiterals name="Increasing"/>
    <eLiterals name="Decreasing" value="1"/>
    <eLiterals name="Flat" value="2"/>
    <eLiterals name="NotMonotonic" value="3"/>
  </eClassifiers>
</ecore:EPackage>
