/*
 * generated by Xtext 2.38.0
 */
package fr.inria.kairos.influence.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.kairos.influence.ide.contentassist.antlr.internal.InternalInfluenceDSLParser;
import fr.inria.kairos.influence.services.InfluenceDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class InfluenceDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(InfluenceDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, InfluenceDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCyberPhysicalPhenomenaAccess().getAlternatives(), "rule__CyberPhysicalPhenomena__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getGroup(), "rule__InfluenceMetamodel__Group__0");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getGroup_3(), "rule__InfluenceMetamodel__Group_3__0");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getGroup_4(), "rule__InfluenceMetamodel__Group_4__0");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getGroup_5(), "rule__InfluenceMetamodel__Group_5__0");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getGroup_6(), "rule__InfluenceMetamodel__Group_6__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup(), "rule__Influence__Group__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_6(), "rule__Influence__Group_6__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_11(), "rule__Influence__Group_11__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_16(), "rule__Influence__Group_16__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_21(), "rule__Influence__Group_21__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_26(), "rule__Influence__Group_26__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_31(), "rule__Influence__Group_31__0");
			builder.put(grammarAccess.getInfluenceAccess().getGroup_36(), "rule__Influence__Group_36__0");
			builder.put(grammarAccess.getArtifactAccess().getGroup(), "rule__Artifact__Group__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup(), "rule__RequirementSatisfaction__Group__0");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getGroup_9(), "rule__RequirementSatisfaction__Group_9__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup(), "rule__SystemResponse__Group__0");
			builder.put(grammarAccess.getSystemResponseAccess().getGroup_3(), "rule__SystemResponse__Group_3__0");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getGroup(), "rule__EmergentBehavior__Group__0");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getGroup_3(), "rule__EmergentBehavior__Group_3__0");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getGroup(), "rule__CyberPhysicalPhenomena_Impl__Group__0");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getGroup_4(), "rule__CyberPhysicalPhenomena_Impl__Group_4__0");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getGroup_4_3(), "rule__CyberPhysicalPhenomena_Impl__Group_4_3__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup(), "rule__MultiPhenomenon__Group__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_4(), "rule__MultiPhenomenon__Group_4__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_4_3(), "rule__MultiPhenomenon__Group_4_3__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_5(), "rule__MultiPhenomenon__Group_5__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_5_3(), "rule__MultiPhenomenon__Group_5_3__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_6(), "rule__MultiPhenomenon__Group_6__0");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getGroup_6_3(), "rule__MultiPhenomenon__Group_6_3__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup(), "rule__SimplePhenomenon__Group__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup_4(), "rule__SimplePhenomenon__Group_4__0");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getGroup_4_3(), "rule__SimplePhenomenon__Group_4_3__0");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getOwnedRequirementSatisfactionAssignment_3_2(), "rule__InfluenceMetamodel__OwnedRequirementSatisfactionAssignment_3_2");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getOwnedCyberPhysicalPhenomenaAssignment_4_2(), "rule__InfluenceMetamodel__OwnedCyberPhysicalPhenomenaAssignment_4_2");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getOwnedArtifactsAssignment_5_2(), "rule__InfluenceMetamodel__OwnedArtifactsAssignment_5_2");
			builder.put(grammarAccess.getInfluenceMetamodelAccess().getOwnedInfluencesAssignment_6_2(), "rule__InfluenceMetamodel__OwnedInfluencesAssignment_6_2");
			builder.put(grammarAccess.getInfluenceAccess().getNameAssignment_1(), "rule__Influence__NameAssignment_1");
			builder.put(grammarAccess.getInfluenceAccess().getSourceArtifactAssignment_5(), "rule__Influence__SourceArtifactAssignment_5");
			builder.put(grammarAccess.getInfluenceAccess().getSourceArtifactAssignment_6_1(), "rule__Influence__SourceArtifactAssignment_6_1");
			builder.put(grammarAccess.getInfluenceAccess().getTargetArtifactAssignment_10(), "rule__Influence__TargetArtifactAssignment_10");
			builder.put(grammarAccess.getInfluenceAccess().getTargetArtifactAssignment_11_1(), "rule__Influence__TargetArtifactAssignment_11_1");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_15(), "rule__Influence__DescriptionAssignment_15");
			builder.put(grammarAccess.getInfluenceAccess().getDescriptionAssignment_16_1(), "rule__Influence__DescriptionAssignment_16_1");
			builder.put(grammarAccess.getInfluenceAccess().getSourcePhenomenaAssignment_20(), "rule__Influence__SourcePhenomenaAssignment_20");
			builder.put(grammarAccess.getInfluenceAccess().getSourcePhenomenaAssignment_21_1(), "rule__Influence__SourcePhenomenaAssignment_21_1");
			builder.put(grammarAccess.getInfluenceAccess().getProducesAssignment_25(), "rule__Influence__ProducesAssignment_25");
			builder.put(grammarAccess.getInfluenceAccess().getProducesAssignment_26_1(), "rule__Influence__ProducesAssignment_26_1");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_30(), "rule__Influence__AffectsAssignment_30");
			builder.put(grammarAccess.getInfluenceAccess().getAffectsAssignment_31_1(), "rule__Influence__AffectsAssignment_31_1");
			builder.put(grammarAccess.getInfluenceAccess().getEvaluatedByAssignment_35(), "rule__Influence__EvaluatedByAssignment_35");
			builder.put(grammarAccess.getInfluenceAccess().getEvaluatedByAssignment_36_1(), "rule__Influence__EvaluatedByAssignment_36_1");
			builder.put(grammarAccess.getArtifactAccess().getNameAssignment_2(), "rule__Artifact__NameAssignment_2");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getNameAssignment_2(), "rule__RequirementSatisfaction__NameAssignment_2");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getConcerningRequirementAssignment_5(), "rule__RequirementSatisfaction__ConcerningRequirementAssignment_5");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_8(), "rule__RequirementSatisfaction__SatisfactionAssignment_8");
			builder.put(grammarAccess.getRequirementSatisfactionAccess().getSatisfactionAssignment_9_1(), "rule__RequirementSatisfaction__SatisfactionAssignment_9_1");
			builder.put(grammarAccess.getSystemResponseAccess().getObservationAssignment_3_1(), "rule__SystemResponse__ObservationAssignment_3_1");
			builder.put(grammarAccess.getEmergentBehaviorAccess().getDescriptionAssignment_3_1(), "rule__EmergentBehavior__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getNameAssignment_2(), "rule__CyberPhysicalPhenomena_Impl__NameAssignment_2");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getConfigurationAssignment_4_2(), "rule__CyberPhysicalPhenomena_Impl__ConfigurationAssignment_4_2");
			builder.put(grammarAccess.getCyberPhysicalPhenomena_ImplAccess().getConfigurationAssignment_4_3_1(), "rule__CyberPhysicalPhenomena_Impl__ConfigurationAssignment_4_3_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getNameAssignment_2(), "rule__MultiPhenomenon__NameAssignment_2");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getConfigurationAssignment_4_2(), "rule__MultiPhenomenon__ConfigurationAssignment_4_2");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getConfigurationAssignment_4_3_1(), "rule__MultiPhenomenon__ConfigurationAssignment_4_3_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getCompositionOfAssignment_5_2(), "rule__MultiPhenomenon__CompositionOfAssignment_5_2");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getCompositionOfAssignment_5_3_1(), "rule__MultiPhenomenon__CompositionOfAssignment_5_3_1");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getAggregationOfAssignment_6_2(), "rule__MultiPhenomenon__AggregationOfAssignment_6_2");
			builder.put(grammarAccess.getMultiPhenomenonAccess().getAggregationOfAssignment_6_3_1(), "rule__MultiPhenomenon__AggregationOfAssignment_6_3_1");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getNameAssignment_2(), "rule__SimplePhenomenon__NameAssignment_2");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getConfigurationAssignment_4_2(), "rule__SimplePhenomenon__ConfigurationAssignment_4_2");
			builder.put(grammarAccess.getSimplePhenomenonAccess().getConfigurationAssignment_4_3_1(), "rule__SimplePhenomenon__ConfigurationAssignment_4_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private InfluenceDSLGrammarAccess grammarAccess;

	@Override
	protected InternalInfluenceDSLParser createParser() {
		InternalInfluenceDSLParser result = new InternalInfluenceDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public InfluenceDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InfluenceDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
